---

- name: Create group for node_exporter
  group:
    name: "{{ node_exporter_group }}"
    gid: 2000
    system: yes
  tags: node_exporter

- name: Create user for node_exporter
  user:
    name: "{{ node_exporter_user }}"
    comment: "Prometheus Node Exporter User"
    group: "{{ node_exporter_group }}"
    uid: 2000
    system: yes
    create_home: no
    shell: /bin/false
  tags: node_exporter

- name: Download and install node_exporter v{{ node_exporter_version }}
  unarchive:
    src: "{{ download_url }}"
    dest: "{{ install_dir }}"
    remote_src: yes
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: 0750
    extra_opts:
      - "node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
      - "--strip-components=1"
  tags: node_exporter

- name: Create systemd unit file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart node_exporter
  tags: node_exporter

- name: Ensure node_exporter is started and enabled
  systemd:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yes
  tags: node_exporter

- meta: flush_handlers
  tags: node_exporter
