def skipStage = false

pipeline {

  agent any

  options {
    buildDiscarder(logRotator(numToKeepStr: '5'))
    durabilityHint('PERFORMANCE_OPTIMIZED')
    ansiColor('xterm')
  }

  stages {

    stage('Skip') {
      steps {
        script {
          skipStage = input(
            message: 'Should we skip stages?',
            ok: 'Yes',
            parameters: [booleanParam(name: 'SKIP_STAGE', defaultValue: false, description: 'Whether to skip a stage.')]
          )
          println(skipStage)
        }
      }
    }

    stage('Build') {
      when {
        expression { skipStage == false }
      }
      steps {
        echo 'Building'
      }
    }

    stage('Push') {
      when {
        expression { skipStage == false }
      }
      steps {
        echo 'Push'
      }
    }

    stage('Test') {
      steps {
        echo 'Test'
      }
    }

    stage('Deploy') {
      steps {
        echo 'Deploy'
      }
    }

  }

}