pipeline {

  agent {
    label 'built-in'
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    durabilityHint('PERFORMANCE_OPTIMIZED')
    ansiColor('xterm')
  }

  environment {
    DIRECTORY = 'pipelines/dockerfiles/tool-box'
    PATH ="/usr/local/bin:$PATH"
  }

  stages {

    stage('Build image') {
      steps {
        dir(env.DIRECTORY) {
          withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'DOCKERHUB_TOKEN', usernameVariable: 'DOCKERHUB_USERNAME')]) {
            withCredentials([[$class: 'VaultTokenCredentialBinding', addrVariable: 'VAULT_ADDR', credentialsId: 'vault-approle', tokenVariable: 'VAULT_TOKEN', vaultAddr: 'http://vault.internal:8200']]) {
              sh 'make login build'
            }
          }
        }
      }
    }

    stage('Scan image'){
      environment {
        // Workaround for trivy to use correct podman socket file
        XDG_RUNTIME_DIR = '/run'
        TRIVY_INSECURE = 'true'
      }
      steps {
        dir(env.DIRECTORY) {
          sh 'make scan'
          recordIssues(
            tools: [trivy(pattern: 'results.json', reportEncoding: 'UTF-8')]
          )
        }
      }
    }

    stage('Tag image') {
      steps {
        dir(env.DIRECTORY) {
          sh 'make tag'
        }
      }
    }

    stage('Push image') {
      steps {
        dir(env.DIRECTORY) {
          sh 'make push'
        }
      }
    }

    stage('Publish image') {
      steps {
        dir(env.DIRECTORY) {
          withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'DOCKERHUB_TOKEN', usernameVariable: 'DOCKERHUB_USERNAME')]) {
            retry(2) {
              sh 'make publish clean'
            }
          }
        }
      }
    }

  }

  post {
    always {
      cleanWs()
    }
  }

}
