pipeline {

  agent none

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    durabilityHint('PERFORMANCE_OPTIMIZED')
    ansiColor('xterm')
  }

  environment {
    DIRECTORY = 'pipelines/dockerfiles/tool-box'
  }

  stages {

    stage('Build image') {
      agent { label 'master' }
      steps {
        dir(env.DIRECTORY) {
          withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'DOCKERHUB_PASSWORD', usernameVariable: 'DOCKERHUB_USERNAME')]) {
            sh 'make login build'
          }
        }
        milestone null
      }
    }

    stage('Tag image') {
      agent { label 'master' }
      steps {
        dir(env.DIRECTORY) {
          sh 'make tag'
        }
      milestone null
      }
    }

    stage('Push image') {
      agent { label 'master' }
      steps {
        dir(env.DIRECTORY) {
          sh 'make push'
        }
        milestone null
      }
    }
/*
    stage('Proceed with publish') {
      options {
        timeout(time: 30, unit: 'MINUTES')
      }
      input {
        message "Ready to publish?"
        ok "Yes, we should."
      }
      steps {
        echo "Approved."
        milestone null
      }
    }
*/
    stage('Publish image') {
      agent { label 'master' }
      steps {
        dir(env.DIRECTORY) {
          withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'DOCKERHUB_PASSWORD', usernameVariable: 'DOCKERHUB_USERNAME')]) {
            retry(2) {
              sh 'make publish'
            }
          }
        }
        milestone null
      }
    }

  }

  post {
    always {
      node('master') {
        cleanWs()
      }
    }
  }

}
