pipeline {

  agent {
    label 'master'
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    durabilityHint('PERFORMANCE_OPTIMIZED')
    ansiColor('xterm')
  }

  environment {
    DIRECTORY = 'pipelines/dockerfiles/tool-box'
    PATH ="/usr/local/bin:$PATH"
  }

  stages {

    stage('Build image') {
      steps {
        dir(env.DIRECTORY) {
          withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'DOCKERHUB_TOKEN', usernameVariable: 'DOCKERHUB_USERNAME')]) {
            sh 'make login build'
          }
        }
        milestone null
      }
    }

    stage('Tag image') {
      steps {
        dir(env.DIRECTORY) {
          sh 'make tag'
        }
        milestone null
      }
    }

// Insecure push not working in img yet

    stage('Push image') {
      steps {
        dir(env.DIRECTORY) {
          sh 'make push'
        }
        milestone null
      }
    }

    stage('Publish image') {
      steps {
        dir(env.DIRECTORY) {
          withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'DOCKERHUB_TOKEN', usernameVariable: 'DOCKERHUB_USERNAME')]) {
            retry(2) {
              sh 'make publish'
            }
          }
        }
        milestone null
      }
    }

  }

  post {
    always {
      node('master') {
        cleanWs()
      }
    }
  }

}
