# Default values for hello-kubernetes application

replicaCount: 2

image:
  repository: centos7.internal:5000/hello-kubernetes
  tag: latest
  pullPolicy: IfNotPresent

container:
  port: 8080

env: {}

resources: {}

psp:
  enabled: false

securityContext:
  allowPrivilegeEscalation: false
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  capabilities:
    drop:
      - all
    add:
      - IPC_LOCK   # required for vault binary
  seccompProfile:
    type: RuntimeDefault

vaultAgent:
  enabled: false
  image:
    repository: vault
    tag: 1.7.0
    pullPolicy: Always
  role: test
  env: {}
  resources: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  host: chart-example.local
  path: /

hpa:
  enabled: false
