pipeline {

  agent any

  options {
    buildDiscarder(logRotator(numToKeepStr: '5'))
    durabilityHint('PERFORMANCE_OPTIMIZED')
    ansiColor('xterm')
  }

  parameters {
    booleanParam(name: 'SKIP_STAGE', defaultValue: false, description: 'Whether to skip a stage.')
  }

  stages {

    stage('Build') {
      when {
        expression { params.SKIP_STAGE == false }
      }
      steps {
        echo 'Building'
      }
    }

    stage('Push') {
      when {
        expression { params.SKIP_STAGE == false }
      }
      steps {
        echo 'Push'
      }
    }

    stage('Deploy') {
      steps {
        echo 'Deploy'
      }
    }

  }

}