---

jenkins_user:  jenkins
jenkins_group: "{{ jenkins_user }}"
jenkins_work_dir: "/var/lib/{{ jenkins_user }}"

redhat_packages:
  - git
  - java-11-openjdk.x86_64
  - unzip
  - curl
  - gnupg2
  - ansible.noarch
# These should be only required on slaves ?
# required to build ansible
  - make
  - rpm-build
  - python-docutils
  - python2-devel
