---

- name: Create Kubernetes config directory
  file:
    path: "{{ jenkins_work_dir }}/.kube"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0700
  tags: jenkins_shared

- name: Add Kubernetes config file
  copy:
    src: config.enc
    dest: "{{ jenkins_work_dir }}/.kube/config"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0600
  tags: jenkins_shared
