---

- name: Include Linux distribution specific tasks
  include_tasks: "packages_{{ ansible_os_family|lower }}.yml"
  tags: jenkins_shared

- name: Add Kubeconfig file
  include_tasks: "kubeconfig.yml"
  tags: jenkins_shared

- name: Install required pip packages
  pip:
    name: "{{ item }}"
    state: present
  loop:
    - packaging
    - Jinja2
    - PyYAML
  tags: jenkins_shared

- name: Load sensitive variables
  include_vars: jenkins.enc.yml
  no_log: True
  tags: jenkins_shared

- name: Add user "jenkins" to sudoers.d
  lineinfile:
    path: /etc/sudoers.d/jenkins
    line: 'jenkins ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'
  tags: jenkins_shared

- name: Create Kubernetes config directory
  file:
    path: "{{ jenkins_work_dir }}/.kube"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0755
  tags: jenkins_shared

- name: Add Kubernetes config file
  copy:
    src: config.enc
    dest: "{{ jenkins_work_dir }}/.kube/config"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0400
  tags: jenkins_shared
