---

- name: Include Linux distribution specific tasks | {{ ansible_os_family|lower }}
  include_tasks: "{{ ansible_os_family|lower }}.yml"
  tags: jenkins_shared

- name: Install required pip packages
  pip:
    name: "{{ item }}"
    state: present
  loop:
    - packaging
    - Jinja2
    - PyYAML
  tags: jenkins_shared

- name: Load sensitive variables
  include_vars: jenkins.enc.yml
  no_log: True
  tags: jenkins_shared

- name: Add user "jenkins" to sudoers.d
  lineinfile:
    path: /etc/sudoers.d/jenkins
    line: 'jenkins ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'
  tags: jenkins_shared

- name: Create Kubernetes config directory
  file:
    path: "{{ jenkins_work_dir }}/.kube"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0755
  tags: jenkins_shared

- name: Add Kubernetes config file
  copy:
    src: config.enc
    dest: "{{ jenkins_work_dir }}/.kube/config"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0400
  tags: jenkins_shared

- name: Get files' content
  set_fact:
    src: "{{ lookup('file', jenkins_work_dir + '/.docker/config.json', errors='ignore') | default('{}', true) }}"
    ecr: "{{ lookup('file', 'credHelpers.json') }}"
  tags: jenkins_shared

- name: Create .docker directory
  file:
    path: "{{ jenkins_work_dir }}/.docker"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0700
  tags: jenkins_shared

- name: Update docker config.json
  copy:
    dest: "{{ jenkins_work_dir }}/.docker/config.json"
    content: "{{ src | combine(ecr) }}"
    group: "{{ jenkins_user }}"
    owner: "{{ jenkins_group }}"
    mode: 0600
  tags: jenkins_shared

- name: Create .ssh directory
  file:
    path: "{{ jenkins_work_dir }}/.ssh"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0700
  tags: jenkins_shared

- name: Copy SSH config file
  copy:
    dest: "{{ jenkins_work_dir }}/.ssh/config"
    src: config
    group: "{{ jenkins_user }}"
    owner: "{{ jenkins_group }}"
    mode: 0644
  tags: jenkins_shared

- name: Add Kubeconfig file
  include_tasks: kubeconfig.yml
  tags: jenkins_shared
