[kube_control_plane]
master-node1 ansible_host=192.168.137.20 ip=192.168.137.20

[etcd:children]
kube_control_plane

[kube_node]
worker-node1 ansible_host=192.168.137.21 ip=192.168.137.21
worker-node2 ansible_host=192.168.137.22 ip=192.168.137.22

[kube:children]
kube_control_plane
kube_node

[kube:vars]
ansible_user=ubuntu
