pipeline {

  agent any

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    disableConcurrentBuilds()
    ansiColor('xterm')
  }

  environment {
    KUBECONFIG = '/home/toolbox/.kube/config'
    ROOT_DIR = 'pipelines/kubernetes/bootstrap/3.3_external_dns'
    REGISTRY = 'http://registry.internal:5000'
    DOCKER_IMAGE = 'registry.internal:5000/tool-box:latest'
    ARGS = '''
      -u toolbox \
      -t \
      --mount type=bind,src=/var/lib/jenkins/.kube,dst=/home/toolbox/.kube,readonly \
      --mount type=bind,src=/var/lib/jenkins/.gnupg,dst=/home/toolbox/.gnupg
    '''
  }

  stages {

    stage('Helm lint & validate') {
      agent {
        docker {
          registryUrl env.REGISTRY
          image env.DOCKER_IMAGE
          alwaysPull true
          args env.ARGS
        }
      }
      steps {
        dir(env.ROOT_DIR) {
          sh '''
            git crypt unlock
            make init lint validate
          '''
        }
      }
    }

    stage('Install external-dns') {
      agent {
        docker {
          registryUrl env.REGISTRY
          image env.DOCKER_IMAGE
          alwaysPull true
          args env.ARGS
        }
      }
      steps {
        dir(env.ROOT_DIR) {
          sh '''
            git crypt unlock
            make init apply
          '''
        }
      }
    }

    stage('Run tests') {
      agent {
        docker {
          image 'constantin07/golang-terratest:1.0.1'
          args '-t --mount type=bind,src=/var/lib/jenkins/.kube,dst=/home/test/.kube,readonly'
        }
      }
      environment {
        GOCACHE = "${WORKSPACE}"
        KUBECONFIG = '/home/test/.kube/config'
      }
      steps {
        dir(env.ROOT_DIR + '/test') {
          sh '''
            go mod download
            go test -count=1 -namespace default
          '''
        }
      }
    }

  }

  post {
    always {
      cleanWs()
    }
  }

}
