version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "pipelines/dockerfiles/tool-box/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "pipelines/dockerfiles/vault/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "pipelines/dockerfiles/jenkins-agent/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "pipelines/dockerfiles/docker-nginx-proxy/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "pipelines/dockerfiles/consul-template/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "pip"
    directory: "ansible/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "python"

  - package-ecosystem: "pip"
    directory: "pipelines/dockerfiles/tool-box/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "python"

  - package-ecosystem: "pip"
    directory: "terraform/vault/config/kubernetes/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "python"
