---

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: .github/workflows/
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directory: terraform/pipeline
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: pipelines/dockerfiles/tool-box/
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: pipelines/dockerfiles/vault/
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: pipelines/dockerfiles/jenkins-agent/
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: pipelines/dockerfiles/docker-nginx-proxy/
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: pipelines/dockerfiles/consul-template/
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: pipelines/dockerfiles/golang-terratest/
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: pipelines/dockerfiles/test-http/
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker

  - package-ecosystem: pip
    directory: ansible/
    schedule:
      interval: weekly
    labels:
      - dependencies
      - python

  - package-ecosystem: pip
    directory: pipelines/dockerfiles/tool-box/
    schedule:
      interval: weekly
    labels:
      - dependencies
      - python
    groups:
      aws-dependencies:
        patterns:
          - awscli
          - boto3

  - package-ecosystem: pip
    directory: terraform/vault/config/kubernetes/
    schedule:
      interval: weekly
    labels:
      - dependencies
      - python

  - package-ecosystem: gomod
    directory: pipelines/kubernetes/bootstrap/3.3_external_dns/test
    schedule:
      interval: weekly
