---

- name: Add HashiCorp GPG key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  tags: vault_binary

- name: Add HashiCorp Linux repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    update_cache: true
    state: present
  tags: vault_binary

- name: Install Vault binary version {{ vault_version }}
  apt:
    name: vault={{ vault_version }}-*
    state: present
    update_cache: true
  tags: vault_binary
