---

- name: Make sure unzip is installed
  package:
    name: unzip
    update_cache: yes
  tags: vault_binary

- name: Install
  tags: vault_binary
  block:

  - name: Download vault v{{ vault_version }} and verify checksum
    get_url:
      url: "{{ vault_url }}"
      dest: "/tmp/{{ vault_package }}"
      checksum: "{{ vault_checksum }}"

  - name: Install vault v{{ vault_version }}
    unarchive:
      src: "/tmp/{{ vault_package }}"
      dest: "{{ vault_install_dir }}"
      remote_src: yes
      mode: 0555

  always:
  - name: Remove temp file v{{ vault_version }}
    file:
      path: "/tmp/{{ vault_package }}"
      state: absent
