---

- name: Install required packages
  apt:
    name: "{{ item  }}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - bash-completion
    - curl

- name: Add GPG key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add repository
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    update_cache: yes
    state: present

- name: Install required Kubernetes packages
  apt:
    name: "{{ item.name  }}={{ item.version }}"
    state: present
    update_cache: yes
  loop:
    - { name: 'kubelet', version: "{{ k8s_version }}" }
    - { name: 'kubeadm', version: "{{ k8s_version }}" }
    - { name: 'kubectl', version: "{{ k8s_version }}" }

- name: Exclude tools from upgrade
  command: apt-mark hold kubelet kubeadm kubectl
