---

- include_tasks: disable_swap.yml

- include_tasks: tune_conntrack.yml

- include_tasks: "{{ ansible_os_family|lower }}.yml"

- include_tasks: calico.yml

# TODO: Run only once per node
#- include_tasks: unique-machine-id.yml
