---

# https://docs.projectcalico.org/v3.7/maintenance/troubleshooting#configure-networkmanager
- name: Tune conn_tracking for Calico
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    ignoreerrors: yes
    sysctl_set: yes
  with_items:
    - { name: net.netfilter.nf_conntrack_max, value: 1000000 }

# https://kubedex.com/90-days-of-aws-eks-in-production/
- name: Network stack optimization
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    ignoreerrors: yes
    sysctl_set: yes
  with_items:
    - { name: net.ipv4.ip_local_port_range, value: "1024 65535" }
    - { name: net.ipv4.tcp_tw_reuse, value: 1 }
    - { name: net.ipv4.tcp_fin_timeout, value: 15 }
    - { name: net.core.somaxconn, value: 4096 }
    - { name: net.core.netdev_max_backlog, value: 4096 }
    - { name: net.core.rmem_max, value: 16777216 }
    - { name: net.core.wmem_max, value: 16777216 }
    - { name: net.ipv4.tcp_max_syn_backlog, value: 20480 }
    - { name: net.ipv4.tcp_max_tw_buckets, value: 400000 }
    - { name: net.ipv4.tcp_no_metrics_save, value: 1 }
    - { name: net.netfilter.nf_conntrack_max, value: 262144 }
