FROM ubuntu:18.04

ARG VAULT_VERSION=1.1.2

RUN apt update && apt -y upgrade && apt install -y curl unzip && \
    curl -O https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip && \
    unzip -d /bin vault_${VAULT_VERSION}_linux_amd64.zip

COPY pull_creds.sh /pull_creds.sh
RUN chmod +x /pull_creds.sh
