---

- name: Download and install helm {{ helm_version }}
  unarchive:
    src: "{{ helm_url }}"
    dest: "{{ install_dir }}"
    remote_src: yes
    extra_opts:
      - "--strip-components=1"
  retries: 3
  delay: 3
  register: res
  until: res is succeeded
  tags: helm

- name: Un-install helm-diff
  ansible.builtin.command: helm plugin uninstall diff
  environment:
    HELM_HOME: '/tmp/.helm'
  ignore_errors: yes
  become: no
  tags: helm

- name: Install helm-diff {{ helm_diff_version }}
  ansible.builtin.command: helm plugin install https://github.com/databus23/helm-diff --version {{ helm_diff_version }} --verify=false
  environment:
    HELM_HOME: '/tmp/.helm'
  become: no
  ignore_errors: yes
  register: result_install
  tags: helm

- name: Update helm-diff
  ansible.builtin.command: helm plugin update diff
  environment:
    HELM_HOME: '/tmp/.helm'
  when: "'plugin already exists' in result_install.stderr"
  become: no
  tags: helm

#- name: Add necessary pip packages
#  ansible.builtin.pip:
#    name: PyYAML==6.0.3
#  tags: helm

# Requires galaxy kubernetes.core collection
- name: Add helm repositories
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
  loop: "{{ helm_repos }}"
  environment:
    HELM_HOME: '/tmp/.helm'
  notify: helm repo update
  become: no
  tags: helm
