---

- name: Download and install helm v{{ helm_version }}
  unarchive:
    src: "{{ helm_url }}"
    dest: "{{ install_dir }}"
    remote_src: yes
    extra_opts:
      - "--strip-components=1"
  retries: 3
  delay: 3
  register: res
  until: res is succeeded
