---

- name: Download and install helm {{ helm_version }}
  unarchive:
    src: "{{ helm_url }}"
    dest: "{{ install_dir }}"
    remote_src: yes
    extra_opts:
      - "--strip-components=1"
  retries: 3
  delay: 3
  register: res
  until: res is succeeded
  tags: helm

- name: Install helm-diff
  command: helm plugin install https://github.com/databus23/helm-diff --version master
  environment:
    HELM_HOME: '/tmp/.helm'
  register: result_install
  ignore_errors: yes
  tags: helm

- name: Update helm-diff
  command: helm plugin update diff
  environment:
    HELM_HOME: '/tmp/.helm'
  when: "'plugin already exists' in result_install.stderr"
  tags: helm

- name: Add necessary pip packages
  pip:
    name: PyYAML
    version: 5.3.1
  tags: helm

# Requires galaxy community.kubernetes collection
- name: Add helm repositories
  community.kubernetes.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
  loop: "{{ helm_repos }}"
  environment:
    HELM_HOME: '/tmp/.helm'
  tags: helm
