---

- include_tasks: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == 'RedHat'

- name: Update /etc/resolv.conf file
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
