---

- include_tasks: "{{ ansible_os_family|lower }}.yml"

- name: Update /etc/resolv.conf file
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  tags: resolv

- name: Update /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '{{ ansible_default_ipv4.address }}'
    line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }} {{ ansible_nodename }}"
    state: present
  when: ansible_default_ipv4.address is defined
  tags: resolv
