---

- name: Update /etc/NetworkManager/NetworkManager.conf file
  lineinfile:
    path: /etc/NetworkManager/NetworkManager.conf
    insertafter: '^\[main\]$'
    line: "dns=none"
    state: present
  notify: restart network_manager
  tags: resolv

- meta: flush_handlers
  tags: resolv
