metricbeat.modules:
  - module: system
    metricsets:
      - cpu
      - filesystem
      - fsstat
      - load
      - memory
      - network
      - process
      - process_summary
      - uptime
    enabled: true
    period: 15s
    processes: ['.*']
    cpu.metrics:  ["percentages"]
    core.metrics: ["percentages"]
    process.cgroups.enabled: true

  - module: docker
    metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network", "image"]
    hosts: ["unix:///var/run/docker.sock"]
    period: 15s

  - module: elasticsearch
    metricsets: ["node", "node_stats"]
    period: 15s
    hosts: ["localhost:9200"]

xpack.monitoring:
  enabled: true
  elasticsearch:

queue:
  mem:
    events: 2048
    flush.min_events: 10
    flush.timeout: 3s

setup.template.name: "metricbeat"
setup.template.pattern: "metricbeat-*"
setup.template.fields: "fields.yml"
setup.template.overwrite: true
setup.template.enabled: true
setup.template.settings:
  index.number_of_shards: 2
  index.number_of_replicas: 0
  _source.enabled: true

setup.dashboards.enabled: true

output.elasticsearch:
  hosts: ["elasticsearch.internal:9200"]
  protocol: http
  index: "metricbeat-%{+yyyy.MM.dd}"
  compression_level: 1

logging.level: warning
logging.metrics.enabled: false
logging.to_files: false
