metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - filesystem
    - memory
    - network
    - process
  enabled: true
  period: 15s
  processes: ['.*']
  cpu_ticks: false

output.elasticsearch:
  hosts: ["elasticsearch.internal:9200"]
  protocol: http
  index: "metricbeat-%{+yyyy.MM.dd}"
  compression_level: 1
