metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - filesystem
    - fsstat
    - load
    - memory
    - network
    - process
    - process_summary
    - uptime
  enabled: true
  period: 15s
  processes: ['.*']
  cpu.metrics:  ["percentages"]
  core.metrics: ["percentages"]
  process.cgroups.enabled: true

- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s

- module: elasticsearch
  metricsets: ["node", "node_stats"]
  period: 10s
  hosts: ["localhost:9200"]

queue:
  mem:
    events: 4096

setup.template.name: "metricbeat-*"
setup.template.pattern: "metricbeat-*"
setup.template.fields: "/usr/share/metricbeat/fields.yml"
setup.template.overwrite: true
setup.template.enabled: true

output.elasticsearch:
  hosts: ["elasticsearch.internal:9200"]
  protocol: http
  index: "metricbeat-%{+yyyy.MM.dd}"
  compression_level: 1
