@Library('global-shared-library') _

import jenkins.model.Jenkins

@NonCPS
def nodeNames() {
  def nodes = []
  jenkins.model.Jenkins.instance.computers.each { c ->
    node = c.getNode()
    if (node.getChannel() != null && node.getNumExecutors() > 0) {
      nodes.add(node.getDisplayName())
    }
  }
  return nodes
}

node() {
  properties([
    buildDiscarder(logRotator(artifactDaysToKeepStr: '', numToKeepStr: '10')),
    pipelineTriggers([cron("TZ=Europe/London\nH/4 * * * *")])
  ])
}

nodeNames().each { node ->
  cleanupDocker(node)
}
