pipeline {

  agent none

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    //disableConcurrentBuilds()
    ansiColor('xterm')
    timeout(time: 1, unit: 'HOURS')
  }

  environment {
    KUBECONFIG = '/home/toolbox/.kube/config'
    DIRECTORY = 'pipelines/kubernetes/kubernetes-dashboard'
    REGISTRY = 'http://centos7.internal:5000'
    DOCKER_IMAGE = 'centos7.internal:5000/tool-box:latest'
    ARGS = '-u toolbox -t --mount type=bind,src=/var/lib/jenkins/.kube,dst=/home/toolbox/.kube,readonly'
  }

  stages {

    stage('Deploy dashboard') {
      agent {
        docker {
          registryUrl env.REGISTRY
          image env.DOCKER_IMAGE
          alwaysPull true
          args env.ARGS
        }
      }
      steps {
        lock('kubernetes/kubernetes-dashboard') {
          dir(env.DIRECTORY) {
            sh 'make validate lint sync'
          }
        }
        cleanWs()
        milestone(ordinal: 1)
      }
    }

    stage('Approve to delete') {
      options {
        timeout(time: 1, unit: 'HOURS')
      }
      steps {
        input(message: 'Do you want to proceed?', ok: 'Yes')
        milestone(ordinal: 2)
      }
    }

    stage('Remove dashboard') {
      agent {
        docker {
          registryUrl env.REGISTRY
          image env.DOCKER_IMAGE
          alwaysPull true
          args env.ARGS
        }
      }
      steps {
        dir(env.DIRECTORY) {
          sh 'make destroy'
        }
        cleanWs()
        milestone(ordinal: 3)
      }
    }


  }

}
