pipeline {

  agent {
    label 'built-in'
  }

  triggers {
    cron('H */4 * * *')
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    disableConcurrentBuilds()
    durabilityHint('PERFORMANCE_OPTIMIZED')
    ansiColor('xterm')
    skipDefaultCheckout()
  }

  environment {
    REGISTRY_HOST = 'centos7.internal:5000'
  }

  stages {

    stage('Clean up files') {
      steps {
        sh '''
          rm -rf $HOME/.cache/trivy
          rm -rf $HOME/.local/share/containers/storage
          rm -rf $HOME/.cache/JNA/temp
          rm -rf $HOME/.helm
          rm -rf $HOME/.packer.d
        '''
      }
    }

  }

}
