pipeline {

  agent {
    label 'built-in'
  }

  triggers {
    cron('H */4 * * *')
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    disableConcurrentBuilds()
    durabilityHint('PERFORMANCE_OPTIMIZED')
    ansiColor('xterm')
    skipDefaultCheckout()
  }

  environment {
    PATH = "/usr/local/bin:$PATH"
  }

  stages {

    stage('Clean up files') {
      steps {
        sh '''
          rm -rf $HOME/.cache/trivy
          rm -rf $HOME/.cache/JNA/temp
          rm -rf $HOME/.helm
          rm -rf $HOME/.packer.d
          rm -rf /tmp/kubeconform/*
        '''
      }
    }

  }

}
