---

- name: Load sensitive data
  include_vars: vault.enc.yml
  no_log: True
  tags: vault_service

- name: Create a vault_logs volume
#  community.docker.docker_volume:
  docker_volume:
    name: vault_logs
  tags: vault_service

- name: Create a vault_data volume
#  community.docker.docker_volume:
  docker_volume:
    name: vault_data
  tags: vault_service

- name: Install Vault service unit file | {{ vault_version }}
  template:
    src: vault-service.service.j2
    dest: /etc/systemd/system/vault-service.service
    owner: root
    group: root
    mode: 0644
  tags: vault_service

- name: Enable and start Vault service
  systemd:
    name: vault-service.service
    enabled: yes
    state: restarted
    daemon_reload: yes
  tags: vault_service

- name: Install Vault unseal unit file
  template:
    src: vault-unseal.service.j2
    dest: /etc/systemd/system/vault-unseal.service
    owner: root
    group: root
    mode: 0644
  tags: vault_service

- name: Enable and start vault-unseal
  systemd:
    name: vault-unseal.service
    enabled: yes
    state: restarted
    daemon_reload: yes
  tags: vault_service
