#!goovy

String root_dir = 'Jenkins/kubernetes/bootstrap'

pipeline {

  agent any

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    disableConcurrentBuilds()
  }

  environment {
    PATH = "$PATH:/usr/local/bin"
  }

  stages {

    stage('Install helm') {
      steps {
        dir("${root_dir}/" + '1_helm_install') {
          sh 'make install'
        }
      }
    }

  }

  post {
    always {
      cleanWs()
    }
  }

}
