#!goovy

String root_dir = 'Jenkins/kubernetes/bootstrap'

pipeline {

  agent any

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    disableConcurrentBuilds()
  }

  environment {
    PATH = "$PATH:/usr/local/bin"
    KUBECONFIG = "$HOME/.kube/config"
  }

  stages {

    stage('Install Calico Overlay') {
      steps {
        dir("${root_dir}/" + '0_overlay_network') {
          sh 'make install'
        }
        milestone(ordinal: 1)
      }
    }

    stage('Install helm') {
      steps {
        dir("${root_dir}/" + '1_helm_install') {
          sh 'make install'
        }
        milestone(ordinal: 2)
      }
    }

    stage('Bootstrap') {
      parallel {
        stage('Install metrics-server') {
          steps {
            dir("${root_dir}/" + '2_metrics_server') {
              sh 'make lint sync'
            }
          }
        }

        stage('Install nginx-ingress') {
          steps {
            dir("${root_dir}/" + '3_nginx_ingress') {
              sh 'make lint sync'
            }
          }
        }
      }
    }

  }

  post {
    always {
      cleanWs()
    }
  }

}
