pipeline {

  agent { label 'master' }

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    disableConcurrentBuilds()
    ansiColor('xterm')
  }

  environment {
    DIRECTORY = 'ansible'
    PYTHONWARNINGS = 'ignore::UserWarning'
  }

  stages {

    stage('Configure Jenkins Slaves') {
      agent {
        docker {
          reuseNode true
          registryUrl 'http://centos7.internal:5000'
          image 'centos7.internal:5000/tool-box:latest'
          alwaysPull true
          args '-u toolbox -v /var/lib/jenkins/.gnupg:/home/toolbox/.gnupg'
        }
      }
      steps {
        dir(env.DIRECTORY) {
          sh 'git crypt unlock'
          sshagent (credentials: ['jenkins-ssh-key']) {
            sh 'ansible jenkins_slaves -m shell -a "yum -y update; yum clean all"'
            sh 'ansible-playbook jenkins_slaves.yml'
          }
        }
      }
    }

  }

  post {
    always {
      cleanWs()
    }
  }

}
