String version = ''

pipeline {

  agent {
    label 'built-in'
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    disableConcurrentBuilds()
    ansiColor('xterm')
  }

  environment {
    DIRECTORY = 'ansible'
    PYTHONWARNINGS = 'ignore::UserWarning'
  }

  stages {

    stage('Deploy docker-registry service') {
      agent {
        docker {
          registryUrl 'http://registry.internal:5000'
          image 'registry.internal:5000/tool-box:latest'
          alwaysPull true
          args '-u toolbox'
        }
      }
      steps {
        dir(env.DIRECTORY) {
          script {
            def playbook = readYaml file: 'docker-registry.yaml'
            playbook[0].roles.findAll { it.getClass() != String }.each { value ->
              if (value.containsKey('registry_version')) {
                version = value.registry_version
              }
            }
            if (!version) {
              error('Could not find version in yaml file.')
            } else {
              currentBuild.description = version
            }
          }
          sshagent (credentials: ['jenkins-ssh-key']) {
            sh 'ansible-playbook docker-registry.yaml'
          }
        }
      }
    }

    stage('Test') {
      steps {
        dir('pipelines/deploy-docker-registry') {
          sh './test.sh'
        }
      }
    }

  }

  post {
    always {
      cleanWs()
    }
  }

}
