---

- name: Set timezone to Europe/London
  timezone:
    name: Europe/London

- name: Install chronyd package
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - chrony

- name: Update /etc/chrony.conf file
  copy:
    src: chrony.conf
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
  notify: restart chronyd

- meta: flush_handlers
