---

- name: Set JAVA_HOME
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: '^JAVA_HOME='
    line: 'JAVA_HOME=/usr/lib/jvm/jre-openjdk'
  tags: jenkins_agent

- name: Add Jenkins group
  group:
    name: "{{ jenkins_group }}"
    gid: "{{ jenkins_group_gid }}"
    state: present
  tags: jenkins_agent

- name: Add Jenkins user
  user:
    name: "{{ jenkins_user }}"
    uid: "{{ jenkins_user_uid }}"
    comment: 'Jenkins user'
    group: "{{ jenkins_group }}"
    groups: docker
    home: "{{ jenkins_work_dir }}"
  tags: jenkins_agent

- name: Create Jenkins work directory
  file:
    path: "{{ jenkins_work_dir }}"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0755
  tags: jenkins_agent

- name: Download Jenkins remoting agent {{ jenkins_remoting_version }}
  get_url:
    url: "{{ jenkins_remoting_url }}"
    dest: "{{ jenkins_bin_path }}/slave.jar"
    force: yes
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0644
  tags: jenkins_agent

- name: Create Jenkins systemd service drop-in directory
  file:
    path: "/etc/systemd/system/{{ jenkins_service_name }}.d"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: jenkins_agent

- name: Install Jenkins systemd unit file
  template:
    src: jenkins-agent.service.j2
    dest: "/etc/systemd/system/{{ jenkins_service_name }}"
    owner: root
    group: root
    mode: 0644
  notify: restart jenkins-agent
  tags: jenkins_agent

- name: Enable Jenkins agent service
  systemd:
    name: "{{ jenkins_service_name }}"
    enabled: yes
    state: started
    daemon_reload: yes
  tags: jenkins_agent
