---

- name: Import gpg key
  rpm_key:
    key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
    state: present

- name: Install elrepo
  yum:
    name: http://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm
    state: present

- name: Install latest kernel
  yum:
    name: kernel-ml
    enablerepo: elrepo-kernel
    disablerepo: "*"
    update_cache: yes
    state: latest

- name: Update /etc/default/grub
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_DEFAULT='
    line: "GRUB_DEFAULT=0"
    state: present
  notify: update grub

- meta: flush_handlers
