---

- name: Remove not required packages | Debian
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - postfix

- name: Install required packages | Debian
  apt:
    name: "{{ debian_packages }}"
    state: latest
