---

- name: Wait for any possibly running unattended upgrade to finish
  raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true

- name: Remove not required packages | Debian
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - postfix

- name: Install required packages | Debian
  apt:
    name: "{{ debian_packages }}"
    state: present
