---

- name: Populate service facts
  service_facts:
  tags: common

- name: Disable firewalld
  systemd:
    name: firewalld
    enabled: no
    state: stopped
  when: "'firewalld' in ansible_facts.services"
  tags: common

