---

- name: Include OS specific tasks
  include_tasks: "{{ ansible_os_family|lower }}.yml"

- include_tasks: disable_firewalld.yml

# Disabled via kernel command-line parameter
#- include_tasks: disable_ipv6.yml
