---

description: 'Build and publish docker image with tools.'

properties:
  githubProjectUrl: 'https://github.com/Constantin07/test'

triggers:
  scm: "H/2 * * * *"

extensions:
  cleanBeforeCheckout: true
  disableRemotePoll: true
  pathRestriction:
    includedRegions: |
      Jenkins/dockerfiles/tool-box/.*

#  cloneOptions:
#    shallow: true
#    noTags: true
