---

description: 'Build and publish docker image with tools.'

properties:
  githubProjectUrl: 'https://github.com/Constantin07/test'

extensions:
  cleanBeforeCheckout: true
  cloneOptions:
    shallow: true
    noTags: true
