pipeline {

  agent any

  triggers {
    pollSCM('H/15 * * * *')
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    disableConcurrentBuilds()
    ansiColor('xterm')
  }

  environment {
    DIRECTORY = 'Jenkins/dockerfiles/tool-box'
  }

  stages {

    stage('Build image') {
      steps {
        dir(env.DIRECTORY) {
          retry(2) { // Handle sporadic errors
            sh 'make build'
          }
        }
      }
    }

    stage('Tag image') {
      steps {
        dir(env.DIRECTORY) {
          sh 'make tag'
        }
      }
    }

    stage('Publish image') {
      steps {
        dir(env.DIRECTORY) {
          sh 'make publish'
        }
      }
    }

  }

  post {
    always {
      cleanWs()
    }
  }

}
