@Library('global-shared-library') _

pipeline {

  agent any

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    disableConcurrentBuilds()
    ansiColor('xterm')
  }

  environment {
    DIRECTORY = 'Jenkins/dockerfiles/tool-box'
  }

  stages {

    stage('Check for changes'){
      steps {
        script {
          if (checkFolderForDiffs(env.DIRECTORY)) {
            echo "Changes detected in directory ${env.DIRECTORY} so continuing"
          } else {
            echo 'No changes detected'
            currentBuild.result = 'ABORTED'
            return
          }
        }
      }
    }

    stage('Build image') {
      steps {
        dir(env.DIRECTORY) {
          retry(2) { // Handle sporadic errors
            sh 'make build'
          }
        }
      }
    }

    stage('Tag image') {
      steps {
        dir(env.DIRECTORY) {
          sh 'make tag'
        }
      }
    }

    stage('Publish image') {
      steps {
        dir(env.DIRECTORY) {
          sh 'make publish clean'
        }
      }
    }

  }

  post {
    always {
      cleanWs()
    }
  }

}
