---

- name: Download and install helm-docs v{{ helm_docs_version }}
  ansible.builtin.unarchive:
    src: "{{ helm_docs_url }}"
    dest: "{{ install_dir }}"
    mode: 0755
    remote_src: true
    exclude:
      - LICENSE
      - README.md
  retries: 3
  delay: 3
  register: res
  until: res is succeeded
  tags: helm_docs
