---

- name: Include OS specific tasks
  include_tasks: "{{ ansible_os_family|lower }}.yml"
  tags: audit

- name: Copy audit.rules file
  copy:
    src: audit.rules
    dest: /etc/audit/rules.d/audit.rules
    owner: root
    group: root
    mode: 0600
  notify: restart auditd
  tags: audit

- name: Ensure auditd is started and enabled
  systemd:
    name: auditd
    enabled: no
    state: stopped
  tags: audit

#- meta: flush_handlers
#  tags: audit
