pipeline {

  agent {
    label 'built-in'
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    disableConcurrentBuilds()
    ansiColor('xterm')
  }

  environment {
    DIRECTORY = 'ansible'
    PYTHONWARNINGS = 'ignore::UserWarning'
  }

  stages {

    stage('Configure K8s nodes') {
      agent {
        docker {
          registryUrl 'http://registry.internal:5000'
          image 'registry.internal:5000/tool-box:latest'
          alwaysPull true
          args '-u toolbox --mount type=bind,src=/var/lib/jenkins/.gnupg,dst=/home/toolbox/.gnupg'
        }
      }
      steps {
        dir(env.DIRECTORY) {
          sh 'git crypt unlock'
          sshagent (credentials: ['jenkins-ssh-key']) {
            sh 'ansible-playbook k8s-nodes.yaml'
          }
        }
      }
    }

  }

  post {
    always {
      cleanWs()
    }
  }

}
