apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "hello-kubernetes.fullname" . }}
  labels: {{- include "hello-kubernetes.labels" . | nindent 4 }}
spec:
  privileged: false  # Don't allow privileged pods!
