---
# Used for testing purposes
# Ref: https://k8s.io/examples/admin/dns/busybox.yaml

apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  serviceAccountName: hello-kubernetes
  containers:
  - name: busybox
    image: busybox:1.30
    imagePullPolicy: Always
    command:
      - sleep
      - "7200"
    env:
      - name: VAULT_ADDR
        value: "http://vault.internal:8200"
    volumeMounts:
    - name: secrets
      mountPath: "/secrets"
  restartPolicy: Always
  volumes:
  - name: secrets
    emptyDir: {}
