---

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos
    image: centos:latest
    pull: True
    privileged: true
  - name: ubuntu
    image: ubuntu:bionic
    pull: True
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
