---

driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos
    image: centos:latest
    pull: True
    privileged: true
  - name: ubuntu
    image: ubuntu:bionic
    pull: True
    privileged: true
provisioner:
  name: ansible
  options:
    v: True
  playbooks:
    converge: playbook.yml
  lint:
    name: ansible-lint
    options:
      force-color: True
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
