---

driver:
  name: docker
lint: |
  yamllint .
platforms:
  - name: centos
    image: centos:8
    pull: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: "/usr/sbin/init"
    tty: True
    privileged: true
    environment:
      container: docker
provisioner:
  name: ansible
  log: True
  playbooks:
    converge: playbook.yml
  lint:
    name: ansible-lint
    options:
      force-color: True
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
