---

description: 'Build and publish Hashi Vault image.'

properties:
  githubProjectUrl: 'https://github.com/hashicorp/terraform'

parameters:
  - name: VAULT_VERSION
    type: stringParam
    defaultValue: '1.1.3'
    description: 'The version of Vault.'

extensions:
  'cleanBeforeCheckout()'
