pipeline {

  agent any

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    disableConcurrentBuilds()
    ansiColor('xterm')
  }

  environment {
    DIRECTORY = 'Jenkins/dockerfiles/vault'
  }

  stages {

    stage('Build image') {
      steps {
        dir(env.DIRECTORY) {
          sh 'make build'
        }
      }
    }

    stage('Tag image') {
      steps {
        dir(env.DIRECTORY) {
          sh 'make tag'
        }
      }
    }

    stage('Publish image') {
      steps {
        dir(env.DIRECTORY) {
          sh 'make publish'
        }
      }
    }

  }

  post {
    always {
      cleanWs()
    }
  }

}
