---

- name: Wait for any possibly running unattended upgrade to finish
  raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true
  tags: bind

- name: Update apt cache
  apt:
    update_cache: true
  tags: bind

- name: Install required packages | Debian
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ debian_packages }}"
  tags: bind

- name: Update /etc/bind/named.conf.options file
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: "{{ bind_user }}"
    group: "{{ bind_group }}"
    mode: 0644
  notify: restart bind
  tags: bind

- name: Start bind service
  service:
    name: named
    state: started
    enabled: true
  tags: bind
