---

- name: Run docker image
  docker_container:
    api_version: auto
    name: "{{ image_name }}"
    image: "{{ docker_host }}/{{ image_name }}:{{ version }}"
    state: started
    recreate: True
    oom_killer: False
    pull: yes
    network_mode: host
    memory: "{{ memory|default('1gb') }}"
    volumes:
      - "/proc:/hostfs/proc:ro"
      - "/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro"
      - "/:/hostfs:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    user: 0
    env:
      DOCKER_HOST: "{{ ansible_nodename|default(ansible_default_ipv4['address']) }}"
    restart_policy: on-failure
    restart_retries: 10
    trust_image_content: true
    log_driver: journald
