---

k8s_version: '1.18.6-00'

debian_packages:
  - apt-transport-https
  - bash-completion
  - curl
  - socat

kubernetes_packages:
  - kubelet={{ k8s_version }}
  - kubeadm={{ k8s_version }}
  - kubectl={{ k8s_version }}
  - kubernetes-cni
