---

k8s_version: 1.30.1
k8s_version_prefix: "{{ k8s_version | ansible.builtin.regex_search('^[0-9]+.[0-9]+') }}"

kubernetes_packages:
  - "kubelet={{ k8s_version }}-*"
  - "kubeadm={{ k8s_version }}-*"
  - "kubectl={{ k8s_version }}-*"
  - kubernetes-cni
