---

k8s_version: '1.19.7-00'

debian_packages:
  - apt-transport-https
  - bash-completion
  - curl
  - software-properties-common
  - socat  # required for kubectl port-forward to work

kubernetes_packages:
  - kubelet={{ k8s_version }}
  - kubeadm={{ k8s_version }}
  - kubectl={{ k8s_version }}
  - kubernetes-cni
