def nodeName = 'master'
def git_url  = 'https://github.com/hashicorp/packer.git'
def sub_dir  = 'go/src/github.com/hashicorp/packer'
def git_hub_project = 'https://github.com/hashicorp/packer/'

node(nodeName){

    properties([
	buildDiscarder(logRotator(artifactDaysToKeepStr: '', numToKeepStr: '20')),
        pipelineTriggers([githubPush(), pollSCM("TZ=Europe/London\nH H(9-18) * * *")]),
        // Allow only one job at a time
        disableConcurrentBuilds(),
        [$class: 'GithubProjectProperty', displayName: '', projectUrlStr: git_hub_project],
    ])

    env.GOHOME = '/usr/local/go'
    env.PATH = "${env.PATH}:${env.GOHOME}/bin:/usr/local/bin/"
    def workspace = pwd()
    env.GOPATH = "${workspace}/go"

    ansiColor('xterm') {

	stage('Checkout') {
	    checkout scm: [$class: 'GitSCM',
		branches: [[name: '*/master']],
		userRemoteConfigs: [[url: git_url ]],
		extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: sub_dir]]
	    ]
	}

	milestone label: 'Checkout'

	dir(sub_dir) {
	    stage('Build') {
		sh 'env GOOS=linux GOARCH=amd64 go build -v -o bin/packer .'
	    }

	    milestone label: 'Build'

	    stage('Install') {
		sh 'sudo cp -f bin/packer /usr/local/bin/packer.io'
		sh 'packer.io version'
	    }
	}
    }
}
