---

description: Clean up old docker images and containers.

triggers:
  cron: 'TZ=Europe/London\nH H/4 * * *'

extensions:
  cleanBeforeCheckout: true
  cloneOptions:
    shallow: true
    noTags: true
