---

- name: Include Linux distribution specific tasks
  include_tasks: "{{ ansible_os_family|lower }}.yml"

- name: Add jenkins user to docker group
  user:
    name: jenkins
    groups: docker
    append: yes

- name: Make sure Jenkins is stopped
  service: name=jenkins state=stopped

- name: Cleanup init.groovy.d directory
  file:
    state: "{{ item }}"
    path: /var/lib/jenkins/init.groovy.d
    owner: jenkins
    group: jenkins
    mode: 0755
  with_items:
    - absent
    - directory

- name: Include secrets
  include_vars: secrets.enc.yml
  no_log: True

- name: Upload Groovy bootstrap scripts
  template:
    src: "{{ item }}"
    dest: "{{ jenkins_home }}/init.groovy.d/{{ item | basename | regex_replace('.j2','') }}"
    owner: jenkins
    group: jenkins
    mode: 0644
  with_fileglob:
    - ../templates/*.groovy.j2
  notify: restart jenkins

- name: Upload list of plugins and install script
  copy:
    src: "{{ item.name }}"
    dest: "{{ jenkins_home }}/{{ item.name }}"
    owner: jenkins
    group: jenkins
    mode: "{{ item.mode }}"
  loop:
    - { name: 'install-plugins.sh', mode: '0755' }
    - { name: 'plugins.txt', mode: '0644' }
  notify: restart jenkins

- name: Cleanup /var/lib/jenkins/plugins directory
  file:
    state: "{{ item }}"
    path: /var/lib/jenkins/plugins
    owner: jenkins
    group: jenkins
    mode: 0755
  with_items:
    - absent
    - directory

- name: Install Jenkins plugins
  shell: "{{ jenkins_home }}/install-plugins.sh < {{ jenkins_home }}/plugins.txt"
  environment:
    REF_DIR: "{{ jenkins_home }}/plugins"
    FAILED: "{{ jenkins_home }}/plugins/failed-plugins.txt"
    JENKINS_UC: "https://updates.jenkins.io"
    JENKINS_UC_LATEST: "http://mirrors.jenkins-ci.org"
  become: yes
  become_user: jenkins

- name: Install Jenkins systemd unit file
  template:
    src: jenkins.service.j2
    dest: /etc/systemd/system/jenkins.service
    owner: root
    group: root
    mode: 0644
  notify: restart jenkins

- name: Ensure Jenkins service is started and enabled
  systemd:
    name: jenkins.service
    state: restarted
    enabled: yes
    daemon_reload: yes
