---

- name: Include Linux distribution specific tasks
  include_tasks: "{{ ansible_os_family|lower }}.yml"

- name: Add jenkins user to docker group
  user:
    name: jenkins
    groups: docker
    append: yes

- name: Empty init.groovy.d directory
  file:
    path: /var/lib/jenkins/init.groovy.d
    state: absent

- name: Create init.groovy.d directory
  file:
    path: /var/lib/jenkins/init.groovy.d
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755

- name: Upload Groovy bootstrap scripts
  template:
    src: "{{ item }}"
    dest: "{{ jenkins_home }}/init.groovy.d/{{ item | basename | regex_replace('.j2','') }}"
    owner: jenkins
    group: jenkins
    mode: 0644
  with_fileglob:
    - ../templates/*.j2
  notify: restart jenkins

- name: Upload list of plugins and install script
  copy:
    src: "{{ item.name }}"
    dest: "{{ jenkins_home }}/{{ item.name }}"
    owner: jenkins
    group: jenkins
    mode: "{{ item.mode }}"
  loop:
    - { name: 'install-plugins.sh', mode: '0755' }
    - { name: 'plugins.txt', mode: '0644' }
  notify: restart jenkins

- name: Install Jenkins plugins
  shell: "{{ jenkins_home }}/install-plugins.sh < {{ jenkins_home }}/plugins.txt"
  environment:
    REF_DIR:    "{{ jenkins_home }}/plugins"
    FAILED:     "{{ jenkins_home }}/plugins/failed-plugins.txt"
    JENKINS_UC: "https://updates.jenkins.io"
  become: yes
  become_user: jenkins

- name: Ensure Jenkins service is started and enabled
  service:
    name: jenkins
    state: started
    enabled: yes
