---

- name: Add Jenkins repository
  get_url:
    url: "{{ jenkins_yum_repo_url }}"
    dest: "/etc/yum.repos.d/jenkins.repo"
    owner: root
    group: root
    mode: 0644
  retries: 5
  delay: 3
  register: result
  until: result is not failed
  tags: jenkins_master

- name: Add Jenkins GPG key.
  rpm_key:
    key: "{{ jenkins_yum_gpg_key }}"
    state: present
  retries: 5
  delay: 3
  register: result
  until: result is not failed
  tags: jenkins_master

- name: Install Jenkins
  yum:
    name: "jenkins-{{ jenkins_version }}-*.noarch"
    allow_downgrade: yes
    state: present
    update_cache: yes
  tags: jenkins_master

- name: Jenkins config - JENKINS_PORT
  lineinfile:
    path: /etc/sysconfig/jenkins
    regexp: '^JENKINS_PORT='
    line: 'JENKINS_PORT="{{ jenkins_port }}"'
  notify: restart jenkins
  tags: jenkins_master

- name: Jenkins config - JENKINS_LISTEN_ADDRESS
  lineinfile:
    path: /etc/sysconfig/jenkins
    regexp: '^JENKINS_LISTEN_ADDRESS='
    line: 'JENKINS_LISTEN_ADDRESS="0.0.0.0"'
  notify: restart jenkins
  tags: jenkins_master

- name: Calculate memory for JVM
  set_fact:
    mem_xms: "{{ ((ansible_memtotal_mb*0.9-700)/2)|int|abs  }}"
    mem_xmx: "{{ (ansible_memtotal_mb*0.9-700)|int|abs }}"
  tags: jenkins_master

- name: Jenkins config - JAVA_OPTIONS
  lineinfile:
    path: /etc/sysconfig/jenkins
    regexp: '^JENKINS_JAVA_OPTIONS='
    line: 'JENKINS_JAVA_OPTIONS="{{ jenkins_system_properties }} -Xms{{ mem_xms }}m -Xmx{{ mem_xmx }}m {{ jenkins_java_options }}"'
  notify: restart jenkins
  tags: jenkins_master
