---

- name: Create mount point directories
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0775
    state: directory
  with_items:
    - "/var/data/elasticsearch"
    - "/var/log/elasticsearch"

- name: Add sysctl configurations
  include_tasks: sysctl.yml

- name: Run docker elasticsearch container
  docker_container:
    api_version: auto
    name: "{{ image_name }}"
    image: "{{ docker_host }}/{{ image_name }}:{{ version }}"
    state: started
    recreate: True
    oom_killer: False
    exposed_ports:
      - "9200"
      - "9300"
#    published_ports:
#      - "9200:9200"
#      - "9300:9300"
    pull: yes
    network_mode: host
    cpu_period: 1000000
    cpu_quota: 2000000
    memory: "{{ memory|default('1gb') }}"
    volumes:
      - "/var/data/elasticsearch:/var/data/elasticsearch:rw"
      - "/var/log/elasticsearch:/var/log/elasticsearch:rw"
    env:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g -Des.enforce.bootstrap.checks=true"
      ELASTIC_PASSWORD: "{{ ELASTIC_PASSWORD }}"
      DOCKER_HOST: "{{ ansible_nodename|default(ansible_default_ipv4['address']) }}"
    restart_policy: always
#    restart_retries: 10
    trust_image_content: true
    ulimits:
      - "nofile:262144:262144"
      - "memlock:-1:-1"
      - "nproc:10000:10000"
    log_driver: journald
