pipeline {

  agent {
    label 'docker'
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    durabilityHint('PERFORMANCE_OPTIMIZED')
    ansiColor('xterm')
    disableResume()
    skipDefaultCheckout()
  }

  environment {
    AWS_DEFAULT_REGION = 'eu-west-1'
  }

  stages {

    stage('Test') {
      steps {
        sh """
          pwd
          ls -la /usr/bin/
          echo Hello
          ps -ef
        """

        withCredentials([[
          $class: 'AmazonWebServicesCredentialsBinding',
          credentialsId: 'Amazon Credentials',
          accessKeyVariable: 'AWS_ACCESS_KEY_ID',
          secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
        ]])
        {
          sh """
            ls -la
            #docker pull public.ecr.aws/cloudwatch-agent/cloudwatch-agent:latest
          """
        }
      }
    }

  }

}
