apiVersion: batch/v1
kind: Job
metadata:
  name: kube-bench-node
  labels:
    app: kube-bench-node
spec:
  template:
    metadata:
      labels:
        app: kube-bench-node
    spec:
      hostPID: true
      containers:
      - name: kube-bench
        image: aquasec/kube-bench:0.2.3
        imagePullPolicy: Always
        args: ["node", "--version", "1.17"]
        volumeMounts:
        - name: var-lib-kubelet
          mountPath: /var/lib/kubelet
        - name: etc-systemd
          mountPath: /etc/systemd
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
        - name: opt-kube-bench-config
          mountPath: /opt/kube-bench/cfg/cis-1.5/node.yaml
          subPath: node.yaml
      restartPolicy: Never
      volumes:
      - name: var-lib-kubelet
        hostPath:
          path: "/var/lib/kubelet"
      - name: etc-systemd
        hostPath:
          path: "/etc/systemd"
      - name: etc-kubernetes
        hostPath:
          path: "/etc/kubernetes"
      - name: opt-kube-bench-config
        configMap:
          name: kube-bench-node-configmap
