apiVersion: batch/v1
kind: Job
metadata:
  name: kube-bench-master
  labels:
    app: kube-bench-master
spec:
  template:
    metadata:
      labels:
        app: kube-bench-master
    spec:
      hostPID: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: kube-bench
        image: aquasec/kube-bench:latest
        imagePullPolicy: Always
        args: ["master", "--version", "1.15"]
        volumeMounts:
        - name: var-lib-etcd
          mountPath: /var/lib/etcd
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
        - name: opt-kube-bench-config
          mountPath: /opt/kube-bench/cfg/cis-1.4/master.yaml
          subPath: master.yaml
      restartPolicy: Never
      volumes:
      - name: var-lib-etcd
        hostPath:
          path: "/var/lib/etcd"
      - name: etc-kubernetes
        hostPath:
          path: "/etc/kubernetes"
      - name: opt-kube-bench-config
        configMap:
          name: kube-bench-master-configmap
