---

- name: Create a docker_registry volume
#  community.docker.docker_volume:
  docker_volume:
    name: docker_registry
  tags: docker_registry

- name: Install docker-registry service unit file | {{ registry_version }}
  template:
    src: docker-registry.service.j2
    dest: /etc/systemd/system/docker-registry.service
    owner: root
    group: root
    mode: 0644
  tags: docker_registry

- name: Enable and start docker-registry service
  systemd:
    name: docker-registry.service
    enabled: yes
    state: restarted
    daemon_reload: yes
  tags: docker_registry
