pipeline {

  agent {
    docker {
      registryUrl 'http://registry.internal:5000'
      image 'registry.internal:5000/tool-box:latest'
      alwaysPull true
      args '-u toolbox --mount type=bind,src=/var/lib/jenkins/.kube,dst=/home/toolbox/.kube,readonly'
    }
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    disableConcurrentBuilds()
    ansiColor('xterm')
  }

  environment {
    KUBECONFIG = '/home/toolbox/.kube/config'
    DIRECTORY = 'pipelines/kubernetes/kube-stresscheck'
  }

  stages {

    stage('Run kube-stresscheck') {
      steps {
        dir(env.DIRECTORY) {
          sh 'make apply'
        }
      }
    }

    stage('Sleep') {
      steps {
        sleep(time: 1, unit: "MINUTES")
      }
    }

    stage('Destroy kube-stresscheck') {
      steps {
        dir(env.DIRECTORY) {
          sh 'make destroy'
        }
      }
    }

  }

  post {
    always {
      cleanWs()
    }
  }

}
