---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-stresscheck
  namespace: "{{ .Env.NAMESPACE }}"
automountServiceAccountToken: false

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kube-stresscheck
  namespace: "{{ .Env.NAMESPACE }}"
  labels:
    app: kube-stresscheck
spec:
  selector:
    matchLabels:
      app: kube-stresscheck
  template:
    metadata:
      labels:
        app: kube-stresscheck
    spec:
      # Allow the pod to run on the master.
      # tolerations:
        # - key: node-role.kubernetes.io/master
        #   effect: NoSchedule
      serviceAccount: kube-stresscheck
      securityContext:
        runAsUser: 0
      containers:
        - name: kube-stresscheck
          image: quay.io/giantswarm/kube-stresscheck:latest
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
            seccompProfile:
              type: RuntimeDefault
