pipeline {

  agent {
    label 'built-in'
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    durabilityHint('PERFORMANCE_OPTIMIZED')
    ansiColor('xterm')
  }

  environment {
    DIRECTORY = 'pipelines/dockerfiles/docker-nginx-proxy'
    PATH = "/usr/local/bin:$PATH"
  }

  stages {

    stage('Static code analysis') {
      agent {
        docker {
          image 'bridgecrew/checkov:latest'
          args "--entrypoint=''"
        }
      }
      steps {
        dir(env.DIRECTORY) {
          sh """
            checkov -d . --skip-check CKV_DOCKER_2 \
            -o cli -o junitxml --output-file-path console,results.xml --soft-fail
          """
          junit skipPublishingChecks: true, testResults: 'results.xml'
        }
      }
    }

    stage('Build image') {
      steps {
        dir(env.DIRECTORY) {
          withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'DOCKERHUB_TOKEN', usernameVariable: 'DOCKERHUB_USERNAME')]) {
            sh 'make login build'
          }
        }
      }
    }

    stage('Scan image'){
      steps {
        dir(env.DIRECTORY) {
          sh 'make scan'
          recordIssues(tools: [trivy(pattern: 'results.json', reportEncoding: 'UTF-8')])
        }
      }
    }

    stage('Tag image') {
      steps {
        dir(env.DIRECTORY) {
          sh 'make tag'
        }
      }
    }

    stage('Push image') {
      steps {
        dir(env.DIRECTORY) {
          withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'DOCKERHUB_TOKEN', usernameVariable: 'DOCKERHUB_USERNAME')]) {
            retry(2) {
              sh 'make push clean'
            }
          }
        }
      }
    }

  }

  post {
    always {
      cleanWs()
    }
  }

}
