pipeline {

  agent none

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    disableConcurrentBuilds()
    ansiColor('xterm')
  }

  environment {
    KUBECONFIG = '/home/toolbox/.kube/config'
    DIRECTORY = 'pipelines/kubernetes/hello-kubernetes/deploy'
    REGISTRY = 'http://centos7.internal:5000'
    DOCKER_IMAGE = 'centos7.internal:5000/tool-box:latest'
    ARGS = '-u toolbox --mount type=bind,src=/var/lib/jenkins/.kube,dst=/home/toolbox/.kube,readonly'
  }

  stages {

    stage('Uninstall') {
      agent {
        docker {
          registryUrl env.REGISTRY
          image env.DOCKER_IMAGE
          alwaysPull true
          args env.ARGS
        }
      }
      steps {
        lock('kubernetes/hello-kubernetes/uninstall') {
          dir(env.DIRECTORY) {
            sh 'make destroy'
          }
          cleanWs()
        }
      }
    }

  }

}
