{{ define "hello-kubernetes.application" }}
- name: {{ .Chart.Name }}
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  imagePullPolicy: {{ .Values.image.pullPolicy }}
  lifecycle:
    preStop:
      exec:
        command: ["/bin/sleep", "30"]
  ports:
    - containerPort: {{ .Values.container.port }}
      protocol: TCP
  startupProbe:
    httpGet:
      path: /health
      port: {{ .Values.container.port }}
      scheme: HTTP
    failureThreshold: 30
    periodSeconds: 5
  livenessProbe:
    httpGet:
      path: /health
      port: {{ .Values.container.port }}
      scheme: HTTP
    failureThreshold: 1
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /
      port: {{ .Values.container.port }}
      scheme: HTTP
    initialDelaySeconds: 10
    periodSeconds: 5
  {{- if .Values.resources }}
  resources:
    {{- toYaml .Values.resources | nindent 4 }}
  {{- end }}
  env:
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
  {{- if .Values.env }}
    {{- range $key, $value := .Values.env }}
    - name: {{ $key }}
      value: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- if .Values.securityContext }}
  securityContext:
    {{- toYaml .Values.securityContext | nindent 4 }}
  {{- end }}
  volumeMounts:
    - name: secrets
      mountPath: /etc/secrets
      readOnly: true
{{- end }}
