{{ define "hello-kubernetes.consul-init" }}
- name: consul-template-init
  image: "{{ .Values.consulTemplate.image.repository }}:{{ .Values.consulTemplate.image.tag }}"
  imagePullPolicy: {{ .Values.consulTemplate.image.pullPolicy }}
  command:
    - "/bin/bash"
    - "-c"
    - "source /home/consul/get_token.sh && /usr/local/bin/consul-template -once -config=/home/consul/config.hcl -log-level=info"
  {{- if .Values.consulTemplate.resources }}
  resources:
    {{- toYaml .Values.consulTemplate.resources | nindent 4 }}
  {{- end }}
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
  {{- if .Values.consulTemplateInit.env }}
  env:
    {{- range $key, $value := .Values.consulTemplateInit.env }}
    - name: {{ $key }}
      value: {{ $value | quote }}
    {{- end }}
  {{- end }}
  volumeMounts:
    - name: secrets
      mountPath: /etc/secrets
    - name: consul-template-config
      mountPath: /home/consul/config.hcl
      subPath: config.hcl
      readOnly: true
    - name: consul-template-config
      mountPath: /home/consul/ca.ctmpl
      subPath: ca.ctmpl
      readOnly: true
    - name: consul-template-config
      mountPath: /home/consul/cert.ctmpl
      subPath: cert.ctmpl
      readOnly: true
    - name: consul-template-config
      mountPath: /home/consul/cert_chain.ctmpl
      subPath: cert_chain.ctmpl
      readOnly: true
    - name: consul-template-config
      mountPath: /home/consul/key.ctmpl
      subPath: key.ctmpl
      readOnly: true
{{- end }}
