{{ define "hello-kubernetes.proxy" }}
- name: proxy
  image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}"
  imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
  volumeMounts:
    - name: secrets
      mountPath: /etc/secrets
{{- end }}
