{{ define "hello-kubernetes.vault" }}
- name: vault-agent
  image: "{{ .Values.vaultAgent.image.repository }}:{{ .Values.vaultAgent.image.tag }}"
  imagePullPolicy: {{ .Values.vaultAgent.image.pullPolicy }}
  command: [ "vault" ]
  args:
    - "agent"
    - "-config=/etc/vault/config.hcl"
    - "-log-level=info"
  livenessProbe:
    exec:
      command:
        - sh
        - -c
        - "nc -vz 127.0.0.1 8200"
    initialDelaySeconds: 5
    periodSeconds: 5
    failureThreshold: 1
  {{- if .Values.vaultAgent.resources }}
  resources:
    {{- toYaml .Values.vaultAgent.resources | nindent 4 }}
  {{- end }}
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 100
    runAsGroup: 1000
    capabilities:
      add:
        - IPC_LOCK
  {{- if .Values.vaultAgent.env }}
  env:
    {{- range $key, $value := .Values.vaultAgent.env }}
    - name: {{ $key }}
      value: {{ $value | quote }}
    {{- end }}
  {{- end }}
  volumeMounts:
    - name: vault-config
      mountPath: /etc/vault/config.hcl
      subPath: config.hcl
      readOnly: true
    - name: vault-config
      mountPath: /etc/vault/secrets.tmpl
      subPath: secrets.tmpl
      readOnly: true
    - name: secrets
      mountPath: /etc/secrets
{{- end }}
