apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-kubernetes.fullname" . }}
  labels: {{- include "hello-kubernetes.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/change-cause: {{ .Values.image.tag | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hello-kubernetes.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hello-kubernetes.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        {{- if .Values.vaultAgent.enabled }}
        checksum/vault-agent-config: {{ include (print $.Template.BasePath "/vault-agent-configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.consulTemplate.enabled }}
        checksum/consul-template-config: {{ include (print $.Template.BasePath "/consul-template-configmap.yaml") . | sha256sum }}
        {{- end }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/name"
                      operator: In
                      values:
                        - {{ include "hello-kubernetes.name" . }}
                topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 2
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "hello-kubernetes.name" . }}
      serviceAccountName: {{ include "hello-kubernetes.fullname" . }}
      terminationGracePeriodSeconds: 60

      {{- if .Values.consulTemplate.enabled }}
      initContainers:
        {{- include "hello-kubernetes.consul-init" . | nindent 8 }}
      {{- end }}

      containers:
        {{- include "hello-kubernetes.application" . | nindent 8 }}
        {{- if .Values.vaultAgent.enabled }}
          {{- include "hello-kubernetes.vault" . | nindent 8 }}
        {{- end }}
        {{- if .Values.consulTemplate.enabled }}
          {{- include "hello-kubernetes.consul" . | nindent 8 }}
        {{- end }}
        {{- if .Values.proxy.enabled }}
          {{- include "hello-kubernetes.proxy" . | nindent 8 }}
        {{- end }}
      volumes:
        - name: secrets
          emptyDir:
            medium: "Memory"
        {{- if .Values.vaultAgent.enabled }}
        - name: vault-config
          configMap:
            name: {{ include "hello-kubernetes.fullname" . }}-vault-agent-config
        {{- end }}
        {{- if .Values.consulTemplate.enabled }}
        - name: consul-template-config
          configMap:
            name: {{ include "hello-kubernetes.fullname" . }}-consul-template-config
        {{- end }}
        {{- if .Values.proxy.enabled }}
        - name: proxy-config
          configMap:
            name: {{ include "hello-kubernetes.fullname" . }}-proxy-config
        {{- end }}
