apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-kubernetes.fullname" . }}
  labels: {{- include "hello-kubernetes.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/change-cause: {{ .Values.image.tag | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hello-kubernetes.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hello-kubernetes.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/vaultAgentConfigMap.yaml") . | sha256sum }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/name"
                      operator: In
                      values:
                        - {{ include "hello-kubernetes.name" . }}
                topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 2
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "hello-kubernetes.name" . }}
              app.kubernetes.io/instance: {{ .Release.Name }}
      serviceAccountName: {{ include "hello-kubernetes.fullname" . }}
      terminationGracePeriodSeconds: 60
      containers:
        {{- include "hello-kubernetes.application" . | nindent 8 }}
        {{- if .Values.vaultAgent.enabled }}
          {{- include "hello-kubernetes.vault" . | nindent 8 }}
        {{- end }}
      volumes:
        - name: secrets
          emptyDir:
            medium: "Memory"
        {{- if .Values.vaultAgent.enabled }}
        - name: vault-config
          configMap:
            name: {{ include "hello-kubernetes.fullname" . }}-vault-agent-config
        {{- end }}
