---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hello-kubernetes.fullname" . }}-network-policy-egress
  labels:
    {{- include "hello-kubernetes.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hello-kubernetes.name" . }}
  policyTypes:
  - Egress
  egress:
  # Access to Vault server
  - to:
    - ipBlock:
        cidr: 10.0.2.4/32
    ports:
    - protocol: TCP
      port: 8200
  # Access to CoreDNS to resolve DNS names
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
