{{/*
# Temporary disabled due to performance issues
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hello-kubernetes.fullname" . }}-network-policy-ingress
  labels:
    {{- include "hello-kubernetes.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hello-kubernetes.name" . }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: default
      podSelector:
        matchLabels:
          app.kubernetes.io/instance: nginx-ingress
    ports:
    - protocol: TCP
      port: 8080
*/}}
