apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hello-kubernetes.fullname" . }}
  labels: {{- include "hello-kubernetes.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hello-kubernetes.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
