{{- if .Values.psp.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hello-kubernetes.fullname" . }}-psp
  labels: {{- include "hello-kubernetes.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [ "policy" ]
    resources: [ "podsecuritypolicies" ]
    verbs: [ "use" ]
    resourceNames: [ "{{ include "hello-kubernetes.fullname" . }}" ]
{{- end }}
