apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-kubernetes.fullname" . }}
  labels: {{- include "hello-kubernetes.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
    {{- if .Values.proxy.enabled }}
      targetPort: {{ .Values.proxy.port }}
    {{- else }}
      targetPort: {{ .Values.container.port }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "hello-kubernetes.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
