#!groovy

pipelineJob('test-job') {
  compressBuildLog()
  definition {
    cpsScm {
      scm {
        git {
          branch('master')
          remote {
            name('origin')
            url('git@github.com:Constantin07/test.git')
            credentials('Git')
          }
        }
      }
    description('Terraform scripts for pki')

    scriptPath('terraform/pki/Jenkinsfile')

    }
  }
}
