#!groovy

def repos = [
  [ url: 'git@github.com:Constantin07/test.git', branch: 'master', credential: 'Git' ]
]

repos.each { repo ->
  node() {
    git branch: repo.branch, credentialsId: repo.credential, url: repo.url
  }
}

/*
folder('project') {
  displayName('project')
}
*/

pipelineJob('test-job') {
  compressBuildLog()
  definition {
    cpsScm {
      scm {
        git {
          branch('master')
          remote {
            name('origin')
            url('git@github.com:Constantin07/test.git')
            credentials('Git')
          }
        }
      }

    scriptPath('terraform/pki/Jenkinsfile')

    }
  }
}
