---

jenkins_yum_repo_url: "http://pkg.jenkins-ci.org/redhat/jenkins.repo"
jenkins_yum_gpg_key:  "https://jenkins-ci.org/redhat/jenkins-ci.org.key"
jenkins_home:         "/var/lib/jenkins"
jenkins_version:      "2.163"
jenkins_port:         "8080"
jenkins_slave_port:   "50000"
jenkins_java_options: "-Djenkins.install.runSetupWizard=false -Dsun.net.inetaddr.ttl=0 -Dhudson.DNSMultiCast.disabled=true"
