---

jenkins_yum_repo_url: "https://pkg.jenkins.io/redhat/jenkins.repo"
jenkins_yum_gpg_key:  "https://pkg.jenkins.io/redhat/jenkins.io.key"
jenkins_home:         "/var/lib/jenkins"
jenkins_version:      "2.233"
jenkins_port:         "8080"
jenkins_slave_port:   "50000"

# More details on tuning https://jenkins.io/blog/2016/11/21/gc-tuning
jenkins_java_options: >-
  -Djava.awt.headless=true -Djenkins.install.runSetupWizard=false -Dsun.net.inetaddr.ttl=0 -Dhudson.DNSMultiCast.disabled=true -Dhudson.udp=-1
  -XX:-BytecodeVerificationLocal -XX:-BytecodeVerificationRemote -XX:+ReduceSignalUsage
  -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:-UseLargePagesIndividualAllocation
  -XX:+UseG1GC
  -XX:+ExplicitGCInvokesConcurrent
  -XX:+ParallelRefProcEnabled
