apiVersion: batch/v1
kind: Job
metadata:
  name: kube-bench-node
  labels:
    app: kube-bench-node
spec:
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      labels:
        app: kube-bench-node
    spec:
      hostPID: true
      containers:
      - name: kube-bench
        image: aquasec/kube-bench:v0.6.5
        imagePullPolicy: Always
        args: ["node", "--version", "1.21"]
        volumeMounts:
        - name: var-lib-kubelet
          mountPath: /var/lib/kubelet
          readOnly: true
        - name: etc-systemd
          mountPath: /etc/systemd
          readOnly: true
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
          readOnly: true
          # /usr/local/mount-from-host/bin is mounted to access kubectl / kubelet, for auto-detecting the Kubernetes version.
          # You can omit this mount if you specify --version as part of the command.
        - name: usr-bin
          mountPath: /usr/bin
          readOnly: true
        - name: opt-kube-bench-config
          mountPath: /opt/kube-bench/cfg/cis-1.6/node.yaml
          subPath: node.yaml
      restartPolicy: Never
      volumes:
      - name: var-lib-kubelet
        hostPath:
          path: "/var/lib/kubelet"
      - name: etc-systemd
        hostPath:
          path: "/etc/systemd"
      - name: etc-kubernetes
        hostPath:
          path: "/etc/kubernetes"
      - name: usr-bin
        hostPath:
          path: "/usr/bin"
      - name: opt-kube-bench-config
        configMap:
          name: kube-bench-node-configmap
