---
apiVersion: batch/v1
kind: Job
metadata:
  name: kube-bench-master
  labels:
    app: kube-bench-master
spec:
  template:
    metadata:
      labels:
        app: kube-bench-master
    spec:
      hostPID: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: kube-bench
        image: aquasec/kube-bench:v0.6.5
        imagePullPolicy: Always
        args: ["master", "--version", "1.21"]
        volumeMounts:
        - name: var-lib-etcd
          mountPath: /var/lib/etcd
          readOnly: true
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
          readOnly: true
        # /usr/local/mount-from-host/bin is mounted to access kubectl / kubelet, for auto-detecting the Kubernetes version.
        # You can omit this mount if you specify --version as part of the command.
        - name: usr-bin
          mountPath: /usr/bin
          readOnly: true
        - name: opt-kube-bench-config
          mountPath: /opt/kube-bench/cfg/cis-1.6/master.yaml
          subPath: master.yaml
      restartPolicy: Never
      volumes:
      - name: var-lib-etcd
        hostPath:
          path: "/var/lib/etcd"
      - name: etc-kubernetes
        hostPath:
          path: "/etc/kubernetes"
      - name: usr-bin
        hostPath:
          path: "/usr/bin"
      - name: opt-kube-bench-config
        configMap:
          name: kube-bench-master-configmap
