---

- name: Download and install helmfile {{ helmfile_version }}
  get_url:
    url: "{{ helmfile_url }}"
    dest: "{{ install_dir }}/helmfile"
    force: yes
    mode: 0755
    tmp_dest: /tmp
  tags: [ helmfile ]