---

description: Build and publish HashiCorp Vault image.

properties:
  githubProjectUrl: 'https://github.com/hashicorp/terraform'

extensions:
  cleanBeforeCheckout: true
  cloneOptions:
    shallow: true
    noTags: true
