---

description: Build and publish Hashi Vault image.

properties:
  githubProjectUrl: 'https://github.com/hashicorp/terraform'

parameters:
  - name: VAULT_VERSION
    type: stringParam
    defaultValue: '1.7.0'
    description: 'The version of Vault.'

extensions:
  cleanBeforeCheckout: true
  cloneOptions:
    shallow: true
    noTags: true
