pipeline {

  agent any

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    disableConcurrentBuilds()
    durabilityHint('PERFORMANCE_OPTIMIZED')
    ansiColor('xterm')
  }

  environment {
    DIRECTORY = 'pipelines/dockerfiles/vault'
  }

  parameters {
    string(name: 'VAULT_VERSION', defaultValue: '1.7.3', description: 'The version of Vault.')
  }

  stages {

    stage('Build image') {
      steps {
        dir(env.DIRECTORY) {
          withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'DOCKERHUB_TOKEN', usernameVariable: 'DOCKERHUB_USERNAME')]) {
            sh 'make login build'
          }
        }
      }
    }

    stage('Tag image') {
      steps {
        dir(env.DIRECTORY) {
          sh 'make tag'
        }
      }
    }

    stage('Publish image') {
      steps {
        dir(env.DIRECTORY) {
          sh 'make publish'
        }
      }
    }

  }

  post {
    always {
      cleanWs()
    }
  }

}
