---

description: Builds and installs locally the latest Ansible from dev branch.

properties:
  githubProjectUrl: 'https://github.com/ansible/ansible/'

extensions:
  cleanBeforeCheckout: true
#  cloneOptions:
#    shallow: true
#    noTags: true
