apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-kubernetes.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "hello-kubernetes.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
  selector:
    app.kubernetes.io/name: {{ include "hello-kubernetes.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
