#!groovy

pipeline {

  agent {
    label 'master'
  }

  triggers {
    cron('H H(9-18) * * *')
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    disableConcurrentBuilds()
  }

  environment {
    REGISTRY = 'centos7.internal'
    IMAGE_NAME = 'docker-registry'
    SERVICE_PORT = '5000'
  }

  stages {
    stage('Prepare') {
      steps {
        checkout([
          $class: 'GitSCM',
          branches: [[name: 'master']],
          userRemoteConfigs: [[credentialsId: 'Git', url: 'git@github.com:docker/distribution-library-image.git']]
        ])
      }
    }

    stage('Build image') {
      dir('amd64') {
      }
    }
  }

}
