#!groovy

pipeline {

  agent {
    label 'master'
  }

  triggers {
    pollSCM('H H(9-18) * * *')
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    disableConcurrentBuilds()
  }

  environment {
    REGISTRY = 'centos7.internal'
    IMAGE_NAME = 'docker-registry'
    SERVICE_PORT = '5000'
  }

  stages {

    stage('Prepare') {
      steps {
        checkout([
          $class: 'GitSCM',
          branches: [[name: 'master']],
          userRemoteConfigs: [[credentialsId: 'Git', url: 'git@github.com:docker/distribution-library-image.git']],
          extensions: [
            [$class: 'CleanBeforeCheckout'],
            [$class: 'RelativeTargetDirectory', relativeTargetDir: 'tmp']
          ]
        ])
      }
    }

    stage('Build image') {
      steps {
        sh('cp -f Jenkins/build-docker-registry/Dockerfile tmp/amd64/')
        dir('tmp/amd64') {
          
        }
      }
    }

  }

}
