---

description: "Clean up docker registry from old images."

triggers:
  upstream:
    threshold: SUCCESS
    projects:
      - dockerfiles/tool-box
      - dockerfiles/vault
      - kubernetes/hello-kubernetes
      - builds/build-docker-registry

extensions:
  cleanBeforeCheckout: true
  cloneOptions:
    shallow: true
    noTags: true
