@Library('global-shared-library')_

def nodeName = ''
def terraform_dir = 'terraform/pki'

pipeline {

  agent none

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    durabilityHint('PERFORMANCE_OPTIMIZED')
    ansiColor('xterm')
  }

  environment {
    DIRECTORY = 'terraform/pki'
    REGISTRY = 'http://centos7.internal:5000'
    DOCKER_IMAGE = 'centos7.internal:5000/tool-box:latest'
    ARGS = '-u toolbox --mount type=bind,src=/var/lib/jenkins/.gnupg,dst=/home/toolbox/.gnupg'
  }

  stages {

    stage('Plan') {
      agent {
        docker {
          registryUrl env.REGISTRY
          image env.DOCKER_IMAGE
          alwaysPull true
          args env.ARGS
        }
      }
      steps {
        dir(env.DIRECTORY) {
          withAWS(credentials: 'Amazon Credentials') {
            sh 'git crypt unlock'
            sh 'make WORKSPACE=default BUCKET=dev-705505438149-terraform-state VARFILE=vars/dev.tfvars plan'
          }
          stash(name: 'plan', includes: 'plan.out,.terraform/**')
        }
        milestone null
      }
    }

    stage('Approve') {
      steps {
        script {
          input(message: "Do you want to proceed?", ok: "Yes")
        }
        milestone null
      }
    }

    stage('Apply') {
      agent {
        docker {
          registryUrl env.REGISTRY
          image env.DOCKER_IMAGE
          alwaysPull true
          args env.ARGS
        }
      }
      steps {
        dir(env.DIRECTORY) {
          withAWS(credentials: 'Amazon Credentials') {
            sh 'git crypt unlock'
            unstash(name: 'plan')
            sh 'make WORKSPACE=default BUCKET=dev-705505438149-terraform-state VARFILE=vars/dev.tfvars apply'
          }
        }
        milestone null
      }
    }

  }


}

//terraform_deploy(nodeName, terraform_dir)
