pipeline {

  agent any

  triggers {
    pollSCM('H/5 * * * *')
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    ansiColor('xterm')
  }

  environment {
    KUBECONFIG = '/home/toolbox/.kube/config'
    ARGS = """
      --entrypoint='' \
      --mount type=bind,src=/var/lib/jenkins/.ansible,dst=/.ansible \
      --mount type=bind,src=/var/lib/jenkins/.cache,dst=/.cache
    """
  }

  stages {
    stage('Ansible lint') {
      agent {
        docker {
          image 'cytopia/ansible-lint:latest'
          alwaysPull true
          args env.ARGS
        }
      }
      steps {
        dir('ansible') {
          sh 'ansible-lint *.yml *yaml'
        }
      }
    }
  }

  post {
    always {
      cleanWs()
    }
  }

}