---

- name: Configure journald
  template:
    src: journald.conf.j2
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: 644
  notify:
    - restart journald

- meta: flush_handlers

- name: Ensure journald is started and enabled
  service:
    name: "systemd-journald"
    state: started
    enabled: yes
