---

- name: Configure journald
  template:
    src: journald.conf.j2
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart journald
  tags: journalctl

- meta: flush_handlers
  tags: journalctl

- name: Ensure journald is started and enabled
  service:
    name: "systemd-journald"
    state: started
    enabled: yes
  tags: journalctl
