---

- name: Include OS specific tasks
  include_tasks: "{{ ansible_os_family|lower }}.yml"

- name: Install Docker
  package:
    name: "{{ item }}"
    state: "{{ docker_package_state }}"
  loop: "{{ docker_packages }}"

- name: Ensure dependant services are started
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - systemd-journald

- name: Create systemd drop-in directory for docker
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Add custom settings to docker drop-in file
  template:
    src: docker.conf.j2
    dest: /etc/systemd/system/docker.service.d/docker.conf
    owner: root
    group: root
    mode: 0644
  notify: restart docker

- name: Create docker config directory
  file:
    path: "/etc/docker"
    owner: root
    group: root
    mode: 0755
    state: directory

#- name: Add sysctl configurations
#  include_tasks: sysctl.yml

- name: Update /etc/docker/daemon.json file
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: restart docker

- name: Ensure Docker is started and enabled at boot
  service:
    name: docker
    state: started
    enabled: yes

- meta: flush_handlers
