---

- name: Include OS specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Install Docker
  package: name="{{ docker_package }}" state="{{ docker_package_state }}"

- name: Install docker-py
  pip: name=docker-py version=1.10.6

- name: Ensure dependant services are started
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - systemd-journald

- name: Create docker config directory
  file:
    path: "/etc/docker"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Add sysctl configurations
  include_tasks: sysctl.yml

- name: Ensure Docker is started and enabled at boot
  service:
    name: docker
    state: started
    enabled: yes

- name: Update /etc/docker/daemon.json file
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: restart docker

- meta: flush_handlers
