---

- hosts: centos7.internal

  roles:
    - common
    - resolv
    - chronyd
    - ctop
    - docker
    - helm
    - helmfile
    - gomplate
    - kubeval
    - krew
    - fzf
    - vault_binary
    - { role: jenkins_master, jenkins_version: "2.277" }
    - prometheus/node_exporter
    - nfs_server
