---

- hosts: centos7.internal

  roles:
#    - common
#    - resolv
#    - chronyd
#    - ctop
#    - docker
#    - helm
#    - helmfile
#    - kubeval
    - { role: jenkins_master, jenkins_version: "2.204" }
