---

- hosts: centos7.internal

  roles:
#    - common
#    - resolv
#    - ctop
#    - docker
#    - shunit2
#    - helm
#    - helmfile
#    - gomplate
    - { role: jenkins_master, jenkins_version: "2.193" }
