---

- hosts: centos7.internal

  roles:
    - common
    - resolv
    - chronyd
    - ctop
    - docker
    - helm
    - helmfile
    - gomplate
    - kubeval
    - krew
    - fzf
    - { role: jenkins_master, jenkins_version: "2.268" }
