---

- hosts: centos7.internal

  roles:
    - common
    - resolv
    - chronyd
    - docker
    - helm
    - helmfile
    - gomplate
    - kubeconform
    - krew
    - fzf
    - vault_binary
    - trivy
    - calicoctl
    - git_chglog
    - shellcheck
    - { role: jenkins_master, jenkins_version: "2.421", enable_https: true }
#    - podman
    - prometheus/node_exporter
#    - nfs_server
