---

- hosts: centos7.internal

  roles:
    - common
    - resolv
    - chronyd
    - ctop
    - docker
    - helm
    - helmfile
    - gomplate
    - kubeval
    - krew
    - fzf
    - vault_binary
    - img
    - trivy
    - calicoctl
    - { role: jenkins_master, jenkins_version: "2.317" }
    - prometheus/node_exporter
#    - nfs_server
