---

- hosts: jenkins_slaves
  become: yes
  become_user: root
  serial: 2
  max_fail_percentage: 10

  roles:
    - common
    - resolv
    - chronyd
    - docker
    - { role: jenkins_slave }
    - gnupg2
