---

- hosts: jenkins_slaves
  become: yes
  become_user: root
  any_errors_fatal: true

  roles:
    - common
    - resolv
    - chronyd
    - docker
    - ctop
    - { role: jenkins_slave }
    - gnupg2
