---

- hosts: jenkins_agents
  become: yes
  become_user: root
  any_errors_fatal: true

  roles:
    - common
    - resolv
    - chronyd
    - docker
    - { role: jenkins_agent }
    - gnupg2
    - prometheus/node_exporter
