---

- hosts: jenkins_agents
  become: yes
  become_user: root
  any_errors_fatal: true

  roles:
    - resolv
    - common
    - chronyd
    - docker
    - git_crypt
    - jenkins_agent
    - prometheus/node_exporter
