---
# Playbook to bootstrap nodes for Kubernetes, both master & slaves

- hosts: kube
  become: yes
  become_user: root

  roles:
   - common
   - resolv
   - docker
   - ctop
   - automatic_updates
   - kube_common
   - kubelet_config
