---
# Playbook to bootstrap nodes for Kubernetes, both master & slaves

- hosts: kube
  become: yes
  become_user: root
  any_errors_fatal: true

  roles:
   - common
   - resolv
   - docker
   - automatic_updates
   - kube_common
   - kubelet_config
   - role: prometheus/node_exporter
