---

- hosts: prometheus
  become: yes
  become_user: root

  roles:
    - common
    - resolv
    - { role: docker, dockremap_enable: true }
    - "prometheus/node_exporter"
    - "prometheus/prometheus"
    - grafana
#    - containerd
