---

- hosts: prometheus
  become: yes
  become_user: root

  roles:
    - common
    - resolv
    - docker
    - prometheus/node_exporter
    - prometheus/prometheus
    - grafana
    - cadvisor
    - containerd
    - cri_containerd

