---

- hosts: server.internal

  roles:
    - resolv
    - common
    - docker
    - helm
    - helmfile
    - gomplate
    - kubeconform
    - fzf
    - vault_binary
    - trivy
##    - calicoctl
    - git_chglog
#    - { role: jenkins_master, jenkins_version: "2.412", enable_https: true }
##    - podman
    - prometheus/node_exporter
##    - nfs_server
