---

- hosts: server.internal

  roles:
    - resolv
    - common
    - docker
    - helm
    - helmfile
    - gomplate
    - kubeconform
    - fzf
    - vault_binary
    - trivy
    - bind
    - git_chglog
    - shellcheck
    - { role: jenkins_master, jenkins_version: "2.421", enable_https: false }
#    - prometheus/node_exporter
##    - nfs_server
