---

- hosts: server.internal

  roles:
    - resolv
    - common
    - docker
    - helm
    - helmfile
    - helm_docs
    - gomplate
    - kubeconform
    - fzf
    - vault_binary
    - trivy
    - bind
    - git_chglog
    - shellcheck
    - nginx
    - { role: jenkins_master, jenkins_version: 2.425, enable_https: true }
    - prometheus/node_exporter
##    - nfs_server
