---

- name: Check if ctop is installed
  stat: path="{{ local_dir }}/ctop"
  register: ctop

- name: Check ctop verion
  shell: "{{ local_dir }}/ctop -v | sed  s/,// | awk '{print $3}'"
  register: ctop_ver
  changed_when: False

- name: Download and install ctop
  get_url:
    url: "{{ ctop_url }}"
    dest: "{{ local_dir }}/ctop"
    force: yes
    owner: root
    group: root
    mode: 0755
    tmp_dest: "/tmp"
    timeout: 20
    validate_certs: yes
  when: "((ctop_ver.stdout != ctop_version) and ctop.stat.exists) or not ctop.stat.exists"
