---

helmDefaults:
  verify: false
  wait: true
  timeout: 300
  historyMax: 10

releases:
  - name: hello-kubernetes
    chart: ./hello-kubernetes
    namespace: {{ requiredEnv "NAMESPACE" }}
    values:
      - image:
          pullPolicy: Always
          tag: {{ requiredEnv "TAG" }}
        env:
          MESSAGE: "Hello world app deployed on Kubernetes!"
          VAULT_ADDR: "http://127.0.0.1:8200"
          VAULT_SECRET_PATH: secret/hello-kubernetes
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 100Mi
        psp:
          enabled: false
        vaultAgent:
          enabled: true
          image:
            repository: vault
            tag: 1.7.1
          role: hello-kubernetes
          env:
            VAULT_ADDR: "http://vault.internal:8200"
            VAULT_SKIP_VERIFY: "true"
          resources:
            requests:
              cpu: 20m
              memory: 20Mi
            limits:
              cpu: 50m
              memory: 64Mi
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: internal
            external-dns.alpha.kubernetes.io/hostname: hello-kubernetes.internal.
            external-dns.alpha.kubernetes.io/ttl: "60"
          host: hello-kubernetes.internal
        hpa:
          enabled: true
