def skipDelete = false

pipeline {

  agent none

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    ansiColor('xterm')
  }

  environment {
    KUBECONFIG = '/home/toolbox/.kube/config'
    DIRECTORY = 'pipelines/kubernetes/hello-kubernetes'
    REGISTRY = 'http://centos7.internal:5000'
    DOCKER_IMAGE = 'centos7.internal:5000/tool-box:latest'
    ARGS = '-u toolbox --mount type=bind,src=/var/lib/jenkins/.kube,dst=/home/toolbox/.kube,readonly'
  }

  stages {

    stage('Build and publish image') {
      agent any
      steps {
        dir(env.DIRECTORY + '/dockerfile') {
          sh 'make build tag publish'
        }
        cleanWs()
        milestone(ordinal: 1)
      }
    }

    stage('Deploy hello-kubernetes app') {
      agent {
        docker {
          registryUrl env.REGISTRY
          image env.DOCKER_IMAGE
          alwaysPull true
          args env.ARGS
        }
      }
      steps {
        lock('kubernetes/hello-kubernetes') {
          dir(env.DIRECTORY) {
            sh 'make lint sync'
          }
          cleanWs()
          milestone(ordinal: 2)
        }
      }
    }

    stage('Skip delete') {
      options {
        timeout(time: 1, unit: 'HOURS')
      }
      steps {
        script {
          skipDelete = input(
            message: 'Should we skip delete?',
            ok: 'Yes',
            parameters: [booleanParam(name: 'SKIP_DELETE', defaultValue: true, description: 'Whether to skip delete stage.')]
          )
          println(skipDelete)
        }
        milestone(ordinal: 3)
      }
    }

    stage('Delete hello-kubernetes app') {
      when {
        expression { skipDelete == false }
      }
      agent {
        docker {
          registryUrl env.REGISTRY
          image env.DOCKER_IMAGE
          alwaysPull true
          args env.ARGS
        }
      }
      steps {
        lock('kubernetes/hello-kubernetes') {
          dir(env.DIRECTORY) {
            sh 'make destroy'
          }
          cleanWs()
          milestone(ordinal: 4)
        }
      }
    }

  }

}
