---

- name: Run docker image
  docker_container:
    api_version: auto
    name: "{{ image_name }}"
    image: "{{ docker_host }}/{{ image_name }}:{{ version }}"
    state: started
    recreate: True
    oom_killer: False
    exposed_ports:
      - "5601"
    published_ports:
      - "5601:5601"
    pull: yes
    network_mode: bridge
    state: started
    memory: "{{ memory|default('1gb') }}"
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    env:
      DOCKER_HOST: "{{ ansible_nodename|default(ansible_default_ipv4['address']) }}"
    restart_policy: on-failure
    restart_retries: 10
    trust_image_content: true
    log_driver: journald
