---

vault_version:     "1.3.0"
vault_checksum:    "sha256:d89b8a317831b06f2a32c56cb86071d058b09d9317b416bb509ce3d01e912eb3"
vault_package:     "vault_{{ vault_version }}_linux_amd64.zip"
vault_url:         "https://releases.hashicorp.com/vault/{{ vault_version }}/{{ vault_package }}"
vault_install_dir: "/usr/local/bin"
