---

version: "v3.3.10"
image_name: "quay.io/coreos/etcd:{{ version }}"

container_name: etcd
memory: "512m"

data_dir: "/etcd-data"
data_volume: "etcd-data"

etcd_certs_dir: "/etc/etcd/certs"

etcd_cluster_name: "etcd-cluster.internal"
