---

description: Builds and installs terraform binary.

properties:
  githubProjectUrl: 'https://github.com/hashicorp/terraform'

extensions:
  cleanBeforeCheckout: true
  cloneOptions:
    shallow: true
    noTags: true
