pipeline {

  agent { label 'master' }

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    disableConcurrentBuilds()
    ansiColor('xterm')
  }

  environment {
    DIRECTORY = 'Jenkins/builds/build-terraform'
  }

  stages {

    stage('Build') {
      steps {
        dir(env.DIRECTORY) {
          sh 'make build'
        }
      }
    }

    stage('Install') {
      environment {
        PATH = "/usr/local/bin:$PATH"
      }
      steps {
        dir(env.DIRECTORY) {
          sh '''
            sudo make install
            terraform version
          '''
        }
      }
    }

    stage('Cleanup') {
      steps {
        dir(env.DIRECTORY) {
          sh 'make clean'
        }
      }
    }

  }

  post {
    always {
      cleanWs()
    }
  }

}
