String project_dir='Jenkins/builds/build-terraform'

pipeline {

  agent any

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    disableConcurrentBuilds()
  }

  stages {

    stage('Build') {
      steps {
        dir("${project_dir}") {
          sh 'make build'
        }
      }
    }

    stage('Install') {
      environment {
        PATH = "/usr/local/bin:$PATH"
      }
      steps {
        dir("${project_dir}") {
          sh '''
            sudo make install
            terraform version
          '''
        }
      }
    }

    stage('Cleanup') {
      steps {
        dir("${project_dir}") {
          sh 'make clean'
        }
      }
    }

  }

  post {
    always {
      cleanWs()
    }
  }

}
