@Library('global-shared-library') _

pipeline {

  agent {
    label 'master'
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    durabilityHint('PERFORMANCE_OPTIMIZED')
    ansiColor('xterm')
  }

  environment {
    DIRECTORY = 'pipelines/dockerfiles/jenkins-agent'
  }

  stages {

    stage('Build image') {
      environment {
        PATH = "/usr/local/bin:$PATH"
      }
      steps {
        dir(env.DIRECTORY) {
          withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'DOCKERHUB_TOKEN', usernameVariable: 'DOCKERHUB_USERNAME')]) {
            sh 'make login build'
          }
        }
        milestone null
      }
    }

    stage('Tag image') {
      environment {
        PATH = "/usr/local/bin:$PATH"
      }
      steps {
        dir(env.DIRECTORY) {
          sh 'make tag'
        }
        milestone null
      }
    }

    stage('Push image') {
      environment {
        PATH = "/usr/local/bin:$PATH"
      }
      steps {
        dir(env.DIRECTORY) {
          withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'DOCKERHUB_TOKEN', usernameVariable: 'DOCKERHUB_USERNAME')]) {
            retry(2) {
              sh 'make push'
            }
          }
        }
        milestone null
      }
    }

  }

  post {
    always {
      cleanImg()
      cleanWs()
    }
  }

}
