#!/usr/bin/env sh

set -e

# Required environment variables :
# * JENKINS_URL : alternate jenkins URL
# * JENKINS_SECRET : agent secret, if not set as an argument
# * JENKINS_AGENT_NAME : agent name, if not set as an argument
# * JENKINS_AGENT_WORKDIR : agent work directory, if not set by optional parameter -workDir

# Optional :
# * JENKINS_TUNNEL : HOST:PORT for a tunnel to route TCP traffic to jenkins host, when jenkins can't be directly accessed over network
# * JENKINS_WEB_SOCKET: true if the connection should be made via WebSocket rather than TCP
# * JENKINS_DIRECT_CONNECTION: Connect directly to this TCP agent port, skipping the HTTP(S) connection parameter download.
#                              Value: "<HOST>:<PORT>"
# * JENKINS_INSTANCE_IDENTITY: The base64 encoded InstanceIdentity byte array of the Jenkins master. When this is set,
#                              the agent skips connecting to an HTTP(S) port for connection info.
# * JENKINS_PROTOCOLS:         Specify the remoting protocols to attempt when instanceIdentity is provided.

if [ $# -eq 1 ]; then
    # if only one argument, assume run command
    exec "$@"
else
    if [ "$JENKINS_WEB_SOCKET" = true ]; then
	WEB_SOCKET=-webSocket
    fi

    if [ -n "$JENKINS_PROTOCOLS" ]; then
	PROTOCOLS="-protocols $JENKINS_PROTOCOLS"
    fi

    if [ -n "$JENKINS_DIRECT_CONNECTION" ]; then
	DIRECT="-direct $JENKINS_DIRECT_CONNECTION"
    fi

    if [ -n "$JENKINS_INSTANCE_IDENTITY" ]; then
	INSTANCE_IDENTITY="-instanceIdentity $JENKINS_INSTANCE_IDENTITY"
    fi

    # if java home is defined, use it
    JAVA_BIN="java"
    if [ "$JAVA_HOME" ]; then
	JAVA_BIN="$JAVA_HOME/bin/java"
    fi

    if [ -n "$JENKINS_NAME" ]; then
	JENKINS_AGENT_NAME="$JENKINS_NAME"
    fi

    exec $JAVA_BIN $JAVA_OPTS -cp /usr/share/jenkins/agent.jar hudson.remoting.jnlp.Main -headless \
    $JENKINS_TUNNEL \
    -url $JENKINS_URL \
    -workDir $JENKINS_AGENT_WORKDIR \
    $WEB_SOCKET \
    $DIRECT \
    $PROTOCOLS \
    $INSTANCE_IDENTITY \
    $JENKINS_SECRET \
    $JENKINS_AGENT_NAME
fi
