pipeline {

  agent {
    label 'built-in'
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
    disableConcurrentBuilds()
    ansiColor('xterm')
  }

  environment {
    DIRECTORY = 'pipelines/builds/build-docker-registry'
    REMOTE_TAG = "${BUILD_NUMBER}-${GIT_COMMIT.substring(0, 8)}"
  }

  stages {

    stage('Build image') {
      steps {
        dir(env.DIRECTORY) {
          sh 'make build tag'
        }
      }
    }

    stage('Publish image') {
      steps {
        dir(env.DIRECTORY) {
          sh 'make push'
        }
      }
    }

    stage('Deploy container') {
      steps {
        dir(env.DIRECTORY) {
          sh 'make deploy'
        }
      }
    }

    stage('Test') {
      steps {
        dir(env.DIRECTORY) {
          sh 'make test'
        }
      }
    }

  }

  post {
    always {
      cleanWs()
    }
  }

}
