---

- name: Download and install terraform-docs {{ tfdocs_version }}
  ansible.builtin.unarchive:
    src: "{{ tfdocs_url }}"
    dest: "{{ install_dir }}"
    mode: 0755
    remote_src: true
    exclude:
      - LICENSE
      - README.md
  retries: 3
  delay: 3
  register: res
  until: res is succeeded
  tags: terraform_docs
