---

- name: Install required packages | Ubuntu
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - apt-transport-https
    - bash-completion
    - software-properties-common
    - socat  # required for kubectl port-forward to work
  tags: kubectl_binary

- name: Add GPG key | Ubuntu
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v{{ k8s_version_prefix }}/deb/Release.key
    keyring: /etc/apt/trusted.gpg.d/kubernetes-apt-keyring.gpg
    state: present
  tags: kubectl_binary

- name: Add repository source list | Ubuntu
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version_prefix }}/deb/ /
    filename: kubernetes
    update_cache: true
    state: present
  tags: kubectl_binary

- name: Install kubectl package v{{ kubectl_version }} | Ubuntu
  apt:
    name: kubectl={{ kubectl_version }}-*
    allow_change_held_packages: true
    allow_downgrade: true
    state: present
    update_cache: true
  tags: kubectl_binary
