name: ansible-lint
run-name: Ansible lint

env:
  DIRECTORY: ansible

on:
  pull_request:
    paths:
      - '${{ env.DIRECTORY }}/**'
      - .github/workflows/ansible-lint.yml

  push:
    paths:
      - 'ansible/**'
      - .github/workflows/ansible-lint.yml
    branches:
      - master

  workflow_dispatch:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.DIRECTORY }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: make deps

      - name: Install collections
        run: make collections

      - name: Run Ansible lint
        run: make lint
