---

name: ansible-lint

on:
  pull_request:
    paths:
      - 'ansible/**'
      - 'kubespray/**'
      - .github/workflows/ansible-lint.yml

  push:
    paths:
      - 'ansible/**'
      - 'kubespray/**'
      - .github/workflows/ansible-lint.yml
    branches: [ master ]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [ansible, kubespray]
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Install dependencies
        run: make deps

      - name: Install collections
        run: make collections

      - name: Run Ansible lint
        run: make lint
