---

name: ansible-lint
run-name: Ansible lint

on:
  pull_request:
    paths:
      - 'ansible/**'
      - .github/workflows/ansible-lint.yml

  push:
    paths:
      - 'ansible/**'
      - .github/workflows/ansible-lint.yml
    branches: [ master ]

  workflow_dispatch:

env:
  DIRECTORY: ansible

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.DIRECTORY }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Install dependencies
        run: make deps

      - name: Install collections
        run: make collections

      - name: Run Ansible lint
        run: make lint
