name: Ansible-lint
run-name: Lint Ansible

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  Ansible-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: make deps

      - name: Install collections
        run: make collections

      - name: Run Ansible lint
        run: make lint
