name: consul-template
run-name: Build consul-template

on:
  pull_request:
    paths:
      - 'pipelines/dockerfiles/consul-template/**'
      - .github/workflows/consul-template.yml

  push:
    paths:
      - 'pipelines/dockerfiles/consul-template/**'
      - .github/workflows/consul-template.yml
    branches:
      - master

  workflow_dispatch:

jobs:
  Build:
    runs-on: [ubuntu-latest, ubuntu-20.04]
    defaults:
      run:
        working-directory: pipelines/dockerfiles/consul-template
    steps:
      - uses: actions/checkout@v3

      - name: Docker login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: make login

      - name: Docker build
        run: make build

      - name: Docker tag
        run: make tag

      - name: Run trivy scan
        uses: aquasecurity/trivy-action@0.8.0
        with:
          image-ref: 'docker.io/constantin07/consul-template:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Docker push
        run: make push

  Checkov-check:
    runs-on: [ubuntu-latest, ubuntu-20.04]
    defaults:
      run:
        working-directory: pipelines/dockerfiles/consul-template
    steps:
      - name: Run Checkov action
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: dockerfile
          skip_check: CKV_DOCKER_2
          output_format: sarif
          output_file_path: checkov-results.sarif
          soft_fail: true

      - name: Upload Checkov results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'checkov-results.sarif'
