name: Kubespray lint

on:
  pull_request:
    paths:
      - 'kubespray/**'
      - .github/workflows/kubespray-lint.yml

  push:
    paths:
      - 'kubespray/**'
      - .github/workflows/kubespray-lint.yml
    branches: [ master ]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  kubespray-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kubespray
    env:
      ANSIBLE_HOST_KEY_CHECKING: "False"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip' # cache pip dependencies

      - name: Install dependencies
        run: make deps

      - name: Install collections
        run: make collections

      - name: Detect Kubespray collection
        id: kubespray
        run: |
          ansible-galaxy collection list

          KS_LINE=$(ansible-galaxy collection list | grep kubernetes_sigs.kubespray)

          if [ -z "$KS_LINE" ]; then
            echo "Kubespray collection not found!"
            exit 1
          fi

          echo "Detected: $KS_LINE"

          KS_VERSION=$(echo $KS_LINE | awk '{print $2}')
          echo "version=$KS_VERSION" >> $GITHUB_OUTPUT

      - name: Show installed versions
        run: |
          echo "Ansible version:"
          ansible --version
          echo "Kubespray version: ${{ steps.kubespray.outputs.version }}"

      - name: Prepare minimal inventory
        run: |
          cat > hosts.yaml <<EOF
all:
  hosts:
    localhost:
      ansible_connection: local
  children:
    kube_control_plane:
      hosts:
        localhost:
    kube_node:
      hosts:
        localhost:
    etcd:
      hosts:
        localhost:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
EOF

      - name: Run dry-run
        run: |
          ansible-playbook -i hosts.yaml cluster.yml --syntax-check
          ansible-playbook cluster.yml --list-tasks
          ansible-playbook cluster.yml --list-hosts
          
