name: Kubespray lint

on:
  pull_request:
    paths:
      - 'kubespray/**'
      - .github/workflows/kubespray-lint.yml

  push:
    paths:
      - 'kubespray/**'
      - .github/workflows/kubespray-lint.yml
    branches: [ master ]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  kubespray-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kubespray
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip' # cache pip dependencies

      - name: Install dependencies
        run: make deps

      - name: Install collections
        run: make collections

      - name: Locate Kubespray directory
        id: locate_kubespray
        run: |
          # Try common locations
          if [ -d "./roles/kubespray" ]; then
            echo "path=./roles/kubespray" >> $GITHUB_OUTPUT
          elif [ -d "./kubespray" ]; then
            echo "path=./kubespray" >> $GITHUB_OUTPUT
          else
            echo "Kubespray not found!"
            ls -R
            exit 1
          fi

      - name: Show Kubespray version (if available)
        run: |
          KS_PATH="${{ steps.locate_kubespray.outputs.path }}"

          if [ -f "$KS_PATH/galaxy.yml" ]; then
            echo "Kubespray galaxy.yml:"
            grep version "$KS_PATH/galaxy.yml" || true
          fi

          if [ -f "$KS_PATH/roles/kubespray-defaults/defaults/main.yml" ]; then
            echo "Defaults file exists"
          fi

      - name: Show installed versions
        run: |
          echo "Ansible version:"
          ansible --version
          echo "Kubespray version:"
          pip show kubespray || echo "Kubespray not installed via pip"

      - name: Run dry-run
        run: |
          # Create fake inventory
          cat <<EOF >> hosts.yaml
          [all]
          localhost ansible_connection=local
          EOF
          
          ansible-playbook -i hosts.yaml cluster.yml --syntax-check
          ansible-playbook cluster.yml --list-tasks
          ansible-playbook cluster.yml --list-hosts
          
