name: pre-commit

on:
  pull_request:
    branches: [master]

  # push:
  #   branches: [master]

  workflow_dispatch:

env:
  terraform_version: 1.16.2
  tflint_version: v0.64.0

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v7

      - name: Cache TFLint plugin dir
        uses: actions/cache@v6
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: ${{ env.tflint_version }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.terraform_version }}

      - name: Setup Python
        uses: actions/setup-python@v7

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
