name: Renovate

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      repoCache:
        description: 'Reset or disable the cache?'
        type: choice
        default: enabled
        options:
          - enabled
          - disabled
          - reset

  schedule:
    - cron: "7,17,27,37,47,57 * * * *" 

concurrency:
  group: renovate-${{ github.repository }}
  cancel-in-progress: false

env:
  cache_dir: /tmp/renovate/cache/renovate/repository
  cache_key: renovate-cache

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      issues: write
      pull-requests: write
      vulnerability-alerts: read
      statuses: write
    steps:
      - name: Restore renovate cache
        id: cache-restore
        if: github.event.inputs.repoCache != 'disabled' && github.event.inputs.repoCache != 'reset'
        uses: actions/cache/restore@v6
        with:
          path: ${{ env.cache_dir }}
          key: ${{ env.cache_key }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            ${{ env.cache_key }}-

      - name: Fix restored cache ownership
        if: steps.cache-restore.outputs.cache-matched-key != ''
        run: |
          sudo chown -R 12021:0 /tmp/renovate/
          ls -R $cache_dir

      - name: Run Renovate
        uses: renovatebot/github-action@v46.3.1
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_GIT_AUTHOR: "Renovate Bot <renovate-bot@users.noreply.github.com>"
          RENOVATE_REPOSITORY_CACHE: ${{ github.event.inputs.repoCache || 'enabled' }}
          LOG_LEVEL: debug
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Save renovate cache
        if: github.event.inputs.repoCache != 'disabled' && steps.cache-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v6.1.0
        with:
          path: ${{ env.cache_dir }}
          key: ${{ env.cache_key }}-${{ github.run_id }}-${{ github.run_attempt }}
