name: tflint

on:
  pull_request:
    paths:
      - 'terraform/**'
      - .github/workflows/tflint.yml
      - '!**/README.md'

  push:
    paths:
      - 'terraform/**'
      - .github/workflows/tflint.yml
      - '!**/README.md'

  workflow_dispatch:

jobs:
  tflint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Cache plugin dir
        uses: actions/cache@v3
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3.0.0
        with:
          tflint_version: v0.46.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.4.5

      - name: Check Terraform formatting
        working-directory: terraform
        run: terraform fmt -recursive -check=true -write=false

      - name: Init TFLint
        run: tflint --init
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        working-directory: terraform
        run: |
          for d in $(ls -d */ | sort | uniq); do
            echo "Checking directory ${d}"
            terraform -chdir="${d}" init -upgrade -backend=false
            tflint --chdir="${d}" --color --config=../../.tflint.hcl
          done
