name: tool-box
run-name: Build tool-box container

on:
  pull_request:
    paths:
      - 'pipelines/dockerfiles/tool-box/**'

  push:
    paths:
      - 'pipelines/dockerfiles/tool-box/**'
    branches:
      - master

  workflow_dispatch:

env:
  IMAGE_NAME: constantin07/tool-box:latest

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pipelines/dockerfiles/tool-box
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          config-inline: |
            [worker.oci]
              max-parallelism = 5

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Copy required files
        run: |
          cp -a ../../../ansible/requirements.yml .
          cp -a ../../../bin .

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          context: pipelines/dockerfiles/tool-box
          platforms: linux/amd64
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: VAULT_CERTS=no_copy
          tags: ${{ env.IMAGE_NAME }}
          load: true

      - name: Run trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Docker push
        run: docker push ${{ env.IMAGE_NAME }}
