name: tool-box
run-name: Build container

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pipelines/dockerfiles/tool-box
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Docker build
        run: |
          cp -a ../../../ansible/requirements.yml .
          cp -a ../../../bin .
          docker build --build-arg VAULT_CERTS=no_copy -t constantin07/tool-box:latest .

      - name: Run trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'constantin07/tool-box:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

#      - name: Docker push
#        run: make push
